### ISSUE TITLE
windows/linux support

### ISSUE THREAD

**Issue by maxogden** [maxogden/menubar#1]
should be doable, I just haven't had time to do it yet. PR welcome!

**Comment by maxogden** [comment]
just published 2.0.11 which makes it work ok on debian w/ xfce4

**Comment by cloudsharl** [comment]
Not work on ubuntu 14.04

**Comment by jenslind** [comment]
@cloudsharl thats because with Unity you have to use `libappindicator1` which has some limitations.
https://github.com/atom/electron/blob/master/docs/api/tray.md

Also see https://github.com/maxogden/menubar/pull/40

**Comment by bbales** [comment]
Is there/will there ever be a workaround to the strange second menu-item click required on linux? @maxogden

**Comment by joeyorlando** [comment]
Any update on this? @maxogden I'm also experiencing the "second menu-item click" on linux

**Comment by maxogden** [comment]
Linux is hard to generally support because of all the desktop environments, if you could open a specific issue for the linux desktop environment, ideally with a pull request and tests, it would be awesome

**Comment by amaurymartiny** [comment]
Prefer to open issues for specific OSes
