### ISSUE TITLE
Is there a way to implement doorhanger UI ?

### ISSUE THREAD

**Issue by bogas04** [maxogden/menubar#100]
It would be a big UI plus

Something like this: 
![screen shot 2015-12-31 at 11 39 20 pm](https://cloud.githubusercontent.com/assets/6177621/12066986/be8e7cdc-b017-11e5-96cb-73ad01a6bb65.png)

**Comment by jenslind** [comment]
See https://github.com/maxogden/menubar/issues/78

**Comment by djyde** [comment]
You could use [Statut](https://github.com/djyde/Statut) or [QuarkShell](https://github.com/HackPlan/quark-shell-mac)
