### ISSUE TITLE
Popover look: the Triangle pointing to the Tray icon

### ISSUE THREAD

**Issue by z-ax** [maxogden/menubar#102]
Hi, is it possible to have a customization like the triangle pointing to app's Tray icon (on OSX/Win at least)?

Like Dropbox, Adobe CC apps have, or similar:
<img width="324" alt="screen shot 2016-01-15 at 16 47 49" src="https://cloud.githubusercontent.com/assets/1391015/12355795/ccf6fd30-bba7-11e5-89a9-f18f33e38c51.png">

Would really appreciate for a direction where should check for it.
Thank you in advance.

**Comment by z-ax** [comment]
Excuses, didn't see the #78, should help with my requirements :)

**Comment by z-ax** [comment]
Support out-of-the-box would be great as well: with native platform shadows, etc.
Could you please check if it's possible?

**Comment by CodeBrauer** [comment]
Is there any way to make the shadow more visible?

**Comment by amaurymartiny** [comment]
I don't think this should be supported out of the box: the arrow belongs to the renderer process, so it should be the end-developer's choice on how to manage HTML/CSS/frontend JS (use SASS? use css-in-js? use plain CSS?...), and add the arrow's styles should be managed by the end-developer.

menubar should not take care of the renderer process. I added [`examples/arrow`](https://github.com/maxogden/menubar/tree/master/examples/arrow) for future inspiration.
