### ISSUE TITLE
Active Tray icon

### ISSUE THREAD

**Issue by pontusab** [maxogden/menubar#103]
Is it possible to get the Tray icon to be active when the windows is open or have i missed something? 

Like this example:
<img width="110" alt="screen shot 2016-01-20 at 13 14 16" src="https://cloud.githubusercontent.com/assets/655158/12448645/bb25e7e6-bf77-11e5-8fac-41c6b981cc5a.png">

**Comment by z-ax** [comment]
:+1:

**Comment by sricho** [comment]
Looking at the `Tray` documentation from Electron it looks as though there is only a hook for changing the icon when it is pressed.

```
mb.on('ready', function ready () {
  mb.tray.setPressedImage('<some_image_name>.png');
})
```

http://electron.atom.io/docs/v0.36.5/api/tray/#tray-setpressedimage-image-os-x

**Comment by z-ax** [comment]
No, it doesn't solve the issue, it's only during click (not the state). Would be cool to toggle highlighted state while main window in shown.

**Comment by pontusab** [comment]
Based on electron documentation there are support for this [setHighlightMode](https://github.com/atom/electron/blob/master/docs/api/tray.md#traysethighlightmodehighlight-os-x).

**Comment by moneytree-doug** [comment]
@sricho It changes the icon properly on mouse click but it releases the pressed image when you mouse up. 

@pontusab The blue state doesn't stay active while the menu is open.

**Comment by davej** [comment]
This is an upstream issue. I remember it being opened as an Electron Issue and zcbens said it was an OS X bug. Either way, it's not something that can be resolved in `menubar`.
