### ISSUE TITLE
Anyone else having issues on Mac 10.11?

### ISSUE THREAD

**Issue by adamjacob** [maxogden/menubar#105]
On Mac 10.11 I can't get the window to show when the menu bar icon is clicked.  Even the example in the repo doesn't seem to be working.  Any ideas?

**Comment by MauriceConrad** [comment]
I have the same problem.

**Comment by pontusab** [comment]
Try to install ver "3.0.0", mine stopped working after the upgrade yesterday.

**Comment by jenslind** [comment]
https://github.com/maxogden/menubar/commit/ea9bdc18c90d4121410d162929b026c4b60efb0d Looks wrong, `menubar.tray` has been replaced with `defaultClickEvent` which is just a string.
Also `loadUrl` and `clicked` is deprecated.

**Comment by maxogden** [comment]
I tested in 10.10, don't have a 10.11 machine to test on. I'll look into
this later today

On Saturday, February 6, 2016, Jens Lind <notifications@github.com> wrote:

> ea9bdc1
> <https://github.com/maxogden/menubar/commit/ea9bdc18c90d4121410d162929b026c4b60efb0d>
> Looks wrong, menubar.tray has been replaced with defaultClickEvent which
> is just a string.
> Also loadUrl and clicked is deprecated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxogden/menubar/issues/105#issuecomment-180812124>.
>


-- 
Sent from my phone

**Comment by maxogden** [comment]
Ahhh!! I had a freaking cached copy of menubar inside my example/node_modules folder. Dang. Fixing now

**Comment by maxogden** [comment]
ok 4.0.2 should fix it
