### ISSUE TITLE
Animation not working?

### ISSUE THREAD

**Issue by soops** [maxogden/menubar#107]
There is an option for animating the width and movement of a BrowserWindow, but when tried with Menubar there is no animation. Am I doing something wrong here?

``` javascript
mb.window.setBounds({
    x: mb.window.getPosition()[0],
    y: mb.window.getPosition()[1],
    width: arg.width,
    height: 500,
    animate: true
});
```

**Comment by jenslind** [comment]
Hello,
looks like the `animate` bool should be passed in as a second argument and not be in the options object.

https://github.com/atom/electron/blob/master/docs/api/browser-window.md#winsetboundsoptions-animate

**Comment by soops** [comment]
This has not worked. Here's my new code:
```javascript
mb.window.setBounds({
    x: mb.window.getPosition()[0],
    y: mb.window.getPosition()[1],
    width: arg.width,
    height: 500
}, true);
```

Still, nothing happens. Any ideas?

**Comment by simonhochrein** [comment]
This issue should be put on the electron repository
