### ISSUE TITLE
Close window

### ISSUE THREAD

**Issue by kareljan** [maxogden/menubar#109]
I'm a noob to electron, so I don't know if this is an electron question or not. 

But how can you close the window. Let's say the user clicks on a button in the window. And I want to close the window?

**Comment by jenslind** [comment]
Menubar exposes a `hideWindow()` method.

```javascript
var menubar = require('menubar')

var mb = menubar()

mb.on('after-show', function () {
  setTimeout(function() {
    mb.hideWindow();
  }, 5000)
})
```

**Comment by kareljan** [comment]
Yes I have Read that in the documentation. But how can you call that From a script Londen in de index.html?

**Comment by jenslind** [comment]
https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md#differences-between-main-process-and-renderer-process

> In Electron, we have several ways to communicate between the main process and renderer processes. Like ipcRenderer and ipcMain ...
