### ISSUE TITLE
Update deprecated options

### ISSUE THREAD

**Issue by zeke** [maxogden/menubar#113]
With the release of electron 0.37 came a bunch of warnings about deprecated options that have been converted to camelCase:

```
(electron) window-position is deprecated. Use windowPosition instead.
```

menubar uses a bunch of these options that now have a deprecated spelling. I'm happy to submit a PR updating these, but I wonder if we should:

a) remove support for the old methods and release a major version bump of `menubar`

or

b) continue supporting all the legacy options with this kind of code:

```js
if (opts['show-dock-icon']) opts.showDockIcon = opts['show-dock-icon']
```

I think I would prefer **option a** for code cleanliness, but I could go either way.

cc @jlord @kevinsawicki

**Comment by jenslind** [comment]
I am voting for option **a**

**Comment by hasit** [comment]
👍 for **a**

**Comment by zeke** [comment]
@maxogden let me know if you want me to open a PR for this.

**Comment by mamal72** [comment]
I think it'll be fixed at #117

**Comment by jenslind** [comment]
`v5.0.0` now uses camelCase for options.

**Comment by zeke** [comment]
Thank you, @jenslind!
