### ISSUE TITLE
Not working show-dock-icon

### ISSUE THREAD

**Issue by fabdelgado** [maxogden/menubar#121]
Create this code for show the icon for electronjs.
Unfortunately it does not work.
The error is:` Build: Error during rollup SyntaxError: Unexpected token (21:8) in /Users/fabiandelgado/desarrollo/tilo-desktop/app/background.js`

```
var menubar = require('menubar')
var mb = menubar()
var opts = {
    show-dock-icon: true
}
mb.on(opts, function ready () {
  console.log('app is ready')
  // your app code here
})

```

**Comment by jeroenbourgois** [comment]
Not sure but should you not put `show-dock-icon` between quotes?

**Comment by fabdelgado** [comment]
I did not try that.
I changed to another implementation.
But the review and I will open again this issue.
