### ISSUE TITLE
Window position completely incorrect on Linux

### ISSUE THREAD

**Issue by joepie91** [maxogden/menubar#123]
Tested using the example app in this repository, on openSUSE 13.1 (64-bits), using XFCE4 (xfce4-panel 4.10.1), and the Electron version as it is installed from the example's package.json.

When clicking the tray icon, the window opens in the top right corner, rather than anywhere near the tray icon:

![selection_622](https://cloud.githubusercontent.com/assets/1663259/15661415/8a49b33c-26e7-11e6-98a8-741b11bef5a4.png)

It does however open on the correct monitor (specifically, the left monitor, which my panel is also displayed on).

**Comment by akashnimare** [comment]
@joepie91 is it fixed? You could try this -

``` javascript
mb.on('ready', () => {
  if (process.platform === 'linux') {
    mb.setOption('x', 930)
    mb.setOption('y', 10)
  }
})
```

**Comment by NelsonBrandao** [comment]
@akashnimare I still get this error, the click bounds returns `x: 0, y: 0`. If I set it manually it works.

**Comment by akashnimare** [comment]
@NelsonBrandao I am able to make it work only by setting it manually.

**Comment by NelsonBrandao** [comment]
@akashnimare @joepie91 We can probably go around this by on tray click get the cursor position `screen.getCursorScreenPoint()`

**Comment by amaurymartiny** [comment]
@joepie91 I'm trying a PR at #223 to solve this issue. If you want to try, it'd be appreciated.

**Comment by evertonfraga** [comment]
Linux is super tricky. Even for a specific linux flavor, it can have several desktop environments. Ubuntu vanilla will always display the taskbar at the top. i could not even change its position.

With Unity desktop environment (on top of ubuntu), its possible to know it using the command
`gsettings get com.canonical.Unity.Launcher launcher-position`

reference: https://www.lifewire.com/move-ubuntu-unity-launcher-bottom-of-screen-4050103

**Comment by evertonfraga** [comment]
I am gathering more information about the issue and might open a PR in the future. Some more findings:

How to reliably get Desktop environment:
https://github.com/electron/electron/blob/c71cdce0b7d450ca49505a226a6738c4f0e01a8e/lib/browser/init.ts#L169

Electron API to check if desktop environment is Unity:
https://electronjs.org/docs/api/app#appisunityrunning-linux

**Comment by Slapbox** [comment]
@maxogden Thanks for your great work!

I've only had time to test one distro so far, which is xfce and has the icon in the bottom right. It works correctly.

So my question is, how/why does it work?

I've poked around the code quite a bit and it specifically says bottom taskbar support on Linux is not implemented? I'm confused how this library finds the correct placement for the icon? Is it using the mouse coordinates to assign a corner? It doesn't seem like it.

I've not been able to figure out how/why this works, can you possibly point me to how this is done?

**Comment by amaurym** [comment]
release in v9.0.5
