### ISSUE TITLE
alwaysOnTop not working

### ISSUE THREAD

**Issue by jescalan** [maxogden/menubar#124]
I'm passing `alwaysOnTop: true` as an option as documented, but the window still hides on blue every time 😢

**Comment by jescalan** [comment]
Ah it looks like the option still needs to be set as `always-on-top`, weird-looking for a js object key. I swear earlier it told me that this was deprecated and to switch to camelCase but maybe I'm crazy. Either way, the hyphenated option works, so feel free to close this. Only leaving it open to see if there's a response about the camelCase thing...

**Comment by simonhochrein** [comment]
`alwaysOnTop` is used as of 1.0.0 and possibly earlier

**Comment by jescalan** [comment]
Why was it changed to being hyphenated?

**Comment by simonhochrein** [comment]
It was hyphenated but they changed it to camelCase:
http://electron.atom.io/docs/api/browser-window/#class-browserwindow

**Comment by jescalan** [comment]
Right, but now things don't match up. This library still uses the hyphenated option: https://github.com/maxogden/menubar/blob/master/index.js#L84

**Comment by simonhochrein** [comment]
Yes, I believe there is a pull request for that
On Jun 3, 2016 8:51 AM, Jeff Escalante <notifications@github.com> wrote:Right, but now things don't match up. This library still uses the hyphenated option: https://github.com/maxogden/menubar/blob/master/index.js#L84

**Comment by jenslind** [comment]
`v5.0.0` now uses camelCase for options.
