### ISSUE TITLE
setOption doesn't do anything

### ISSUE THREAD

**Issue by joepie91** [maxogden/menubar#125]
It seems that `setOption` doesn't actually affect anything. It changes a value in the `opts` object, but this object is only merged into the BrowserWindow options along with defaults and used in various other places during menubar creation. None of these 'destinations' are modified when the `opts` values are.

**Comment by simonhochrein** [comment]
`setOption` can only be called before the window has been initialized,
Although there are a wide variety of [methods](http://electron.atom.io/docs/api/browser-window/#methods) that you can use afterwards with the `menubar.window`
