### ISSUE TITLE
How to hide the fullscreen icon in mac osx?

### ISSUE THREAD

**Issue by moneytree-doug** [maxogden/menubar#126]
I want to hide this: 
![screen shot 2016-06-02 at 5 26 56 pm](https://cloud.githubusercontent.com/assets/7564255/15738671/4b59dfd8-28e7-11e6-95f7-e33475d64047.png)

**Comment by simonhochrein** [comment]
Please provide your menu bar usage code.
That bar shouldn't actually be there.

**Comment by moneytree-doug** [comment]
@simonhochrein It was showing it already from the basic example. FYI, I am using OS X 10.9.5.

Here is my updated menu.js:

```var menubar = require('menubar');
var mb = menubar(options = {
  'dir': 'dist',
  width: 320,
  height: 320,
  'preload-window': true,
  icon: './electron/images/menubaricon.png'
});

mb.on('ready', function ready () {
  console.log('app is ready');
  // your app code here


});


mb.on('after-create-window', function() {
  mb.window.openDevTools();
  mb.tray.setPressedImage('./electron/images/menubaricon_active.png');
  mb.tray.setHighlightMode(true);
});

```

**Comment by simonhochrein** [comment]
try removing ```'preload-window': true```
and also the library might not support that version of OSX

**Comment by moneytree-doug** [comment]
@simonhochrein No change.

**Comment by simonhochrein** [comment]
very strange....
-----Original Message-----

**Comment by davej** [comment]
@moneytree-doug Can't recreate in OS X 10.10 or 10.11. Did you try adding the option: `fullscreenable: false`?

**Comment by iceboxx89** [comment]
`mb = menubar(
  tooltip: "BotVFX QT Generation Server"
  width: 400
  height: 500
  fullscreenable: false
  resizable: false
)`
the above works for me on OS X 10.9 thanks @davej
