### ISSUE TITLE
followed the readme and i get a doc page

### ISSUE THREAD

**Issue by chovy** [maxogden/menubar#130]
I made an index.js and index.html with "hello world" but when I run it as instructed in README.md I get some default app that shows Electron documentation.

**Comment by Savjee** [comment]
Same for me...

**Comment by ewnd9** [comment]
Manually setting the project directory works for me.

```js
const mb = menubar({
  dir: __dirname
})
```

**Comment by Savjee** [comment]
Awesome! Works for me!

**Comment by jenslind** [comment]
The doc page is displayed if index.html cant be found. If `dir` is not specified `app.getAppPath()` will be used. :)

**Comment by ewnd9** [comment]
Probably there was a bug with `app.getAppPath()` on the previous versions. 

```js
const mb = menubar()
```

Correctly opens `index.html` in the same directory on `electron-prebuilt@1.2.3`
