### ISSUE TITLE
dynamic icon ?

### ISSUE THREAD

**Issue by zianwar** [maxogden/menubar#134]
is it possible to display a dynamic icon like a loader for example?

**Comment by steezeburger** [comment]
Or something like scrolling text?

**Comment by TGOlson** [comment]
You can use `md.tray.setImage` to update the tray icon. I'd imagine you can combine that with some nifty `setTimeout` logic to do something interesting.

**Comment by benjam1n** [comment]
It's been a while but I was also looking for the solution and haven't found anything, so here's something I did:

```javascript
setIcon (type) {
  if (type == 'active'){
    this.tray.setImage(settings.get('icons.tray.active'))
  } else if (type == 'default'){
    this.tray.setImage(settings.get('icons.tray.default'))
  }
}
```
```javascript
var trayAnimation = setInterval(() => {
  setTimeout(() => {
    this.parent.setIcon('active')
  }, 300)
  setTimeout(() => {
    this.parent.setIcon('default')
  }, 600)
}, 600)
```
...and when you want to stop the animation:

```javascript
clearInterval(trayAnimation)
```

**Comment by lucaorio** [comment]
Is anyone aware of a way (or workaround) to display some dynamic text?

**Comment by amaurymartiny** [comment]
Does someone want to add a small example app in the `examples/` folder?

**Comment by rwwagner90** [comment]
I'm looking to be able to use an svg, and change the colors. Does anyone know if that is possible?

**Comment by amaurymartiny** [comment]
Have a look at this example @andriyor https://github.com/maxogden/menubar/tree/master/examples/icon-animation
