### ISSUE TITLE
Example app does not build correctly

### ISSUE THREAD

**Issue by salcido** [maxogden/menubar#135]
When testing out the Example app within Menubar, I am able to run it with with `electron .`, however building the app with `electron-packager . Example --platform=darwin --arch=x64 --version=0.36.0 --icon=Icon.icns` results in "Uncaught Exception: Error cannot find module 'menubar'". 

#### Which version of menubar are you using?

`^5.0.0`

#### What cli arguments are you passing?

`electron-packager . Example --platform=darwin --arch=x64 --version=0.36.0 --icon=Icon.icns`

#### What platform are you running menubar on?

OS X 10.11.1

#### Is there a stack trace in the error message you're seeing?

![Screenshot](https://cloud.githubusercontent.com/assets/12960237/16895939/95b011b4-4b39-11e6-9119-2b80c0e971af.png)

#### If possible, please provide instructions to reproduce your problem

`npm install menubar --save`

Change into `Example` directory

Run `electron .`

The app runs correctly as it appears in the menubar.

Build the app with `electron-packager . Example --platform=darwin --arch=x64 --version=0.36.0 --icon=Icon.icns`

An error (as seen above) occurs when attempting to launch the app with the exported file.

**Comment by jenslind** [comment]
Did you run `npm install` inside the example dir?

**Comment by salcido** [comment]
Nope. Works now. Thanks! 😳
