### ISSUE TITLE
Menu style could be customized?

### ISSUE THREAD

**Issue by larryisthere** [maxogden/menubar#136]
Styling like ProductHunt, Craft and Dropbox, it will seem more suitable, because what it contains are not menu items, but kind of a web page.

**Comment by noahbenham** [comment]
Is this still a concern for you @larryisthere or can this be closed? Menubar is intended to be a small webpage. If you'd prefer menu items from the app tray, I'd suggest using electron's built-in [tray context menu](https://github.com/electron/electron/blob/master/docs/api/tray.md).

**Comment by larryisthere** [comment]
Thank you, no more problem.

Thanks,
Xiaoliang

2017年2月7日 +0800 AM7:09 Noah Benham <notifications@github.com>，写道：

**Comment by noahbenham** [comment]
Great! Feel free to close this @larryisthere. I'm not an admin on this repo..just helping out.
