### ISSUE TITLE
Can't change icon using setOption('icon', ...)

### ISSUE THREAD

**Issue by jmvallejo** [maxogden/menubar#138]
After the menu is created I can't change the tray icon using the setOption function, is there another way to do it? Or a workaround?

**Comment by rootscript** [comment]
I was wondering about this too.  Is the following code correct?
```
mb.setOption('width', 640);
mb.setOption('icon', 'icons/myicon-20w.png');
```
I can't seem to find a working example of how to change the menubar options, after the window has been created.

**Comment by jenslind** [comment]
Use `tray.setImage` to change the actual tray icon.

```javascript
mb.on('ready', function ready () {
  mb.tray.setImage('asd.png')
})
```

**Comment by rootscript** [comment]
@jenslind **thanks for your help Jens**.  Very much appreciated.

Just in case it helps someone else, here are the parts that make a button to change the tray icon:

`main.js`
```javascript
const electron = require('electron')
const ipcMain= electron.ipcMain

ipcMain.on("changeIcon", function() {
    mb.tray.setImage('icons/myNewIcon.png')
})
```

`index.html`
```html
<button id="someid" onclick="const {ipcRenderer} = require('electron');ipcRenderer.send('changeIcon');">Press me to change the Tray icon
</button>
```

**Comment by jenslind** [comment]
👍
