### ISSUE TITLE
How to use custom Tray if cannot create Tray before app ready?

### ISSUE THREAD

**Issue by RyanEwen** [maxogden/menubar#139]
Hi there,

I'm trying to use my own Tray instance so that I can add a 'Quit' option to the tray menu, but since menubar creates the app instance, I can't make the tray after the app is ready but before creating menubar. 

How do I create my own Tray instance before the menubar instance?

**Comment by jenslind** [comment]
You could set the trays menu by calling `menubar.tray.setContextMenu`.

**Comment by FreeMasen** [comment]
I was able to make this work with the below example.

``` nodejs
const menubar = require('menubar')
const {Menu} = require('electron')
let mb = menubar()

const contextmenu = Menu.createFromTemplate([
    {label: 'Quit', click() { mb.app.quit() }
])

mb.on('ready', () => {
    mb.tray.setContextMenu(contextMenu)
}
```

**Comment by RyanEwen** [comment]
Thanks
