### ISSUE TITLE
Option to set dock icon?

### ISSUE THREAD

**Issue by kknopper** [maxogden/menubar#140]
I've been trying to set a custom icon for my app - mainly for notifications. It looks like electron needs me to set an icon image path in the BrowserWindow options to do this. I see that menubar has an option to show the dock icon but this just shows the default electron icon. Can there be an option added in the case a user wants a custom dock icon as well? 

I've been trying to access the window through mb.window so I can set an icon myself, but this keeps giving me an error as undefined. Can anyone help me out? Any help would be appreciated.

Thanks!

**Comment by rootscript** [comment]
@kknopper  - Not sure exactly which platform you are on (Mac Win Linux)?, or exactly which icon you want to change, but here are a few: `app.dock.setIcon(image)` for macOS, the JumpListItem `iconPath` is a Windows thing (I think these take .ico files).  There is also one I use for the tray in OS X, which is set by `mb.tray.setImage('./image.png')`

Hope that helps a little!

**Comment by daniellmb** [comment]
Thanks for the tip @rootscript, worked for me! It's confusing because the readme says that it returns a window object. But if you run `console.dir(mb);` you'll see it's not there.

**Comment by FreeMasen** [comment]
Are you examining the object after the 'ready' event?

**Comment by kknopper** [comment]
@rootscript 
The `app.dock.setIcon(image)` was what I was looking for, thank you!
Will setting the dock Icon also affect the notification icon image? I'm still getting the default atom icon there. I haven't tried packaging my app yet though, so not sure if that fixes it.

**Comment by thompsonemerson** [comment]
```javascript
const path = require('path')
let tray

// define the tray
mb.on('after-create-window', () => {
    tray = mb.tray
})

// set image
let changeIcon = () => {
    tray.setImage(path.join(__dirname, 'img', 'newIcon.png'))
}
```

I hope I have helped! ;)

**Comment by noahbenham** [comment]
Hey @kknopper, did that work for you? Can this be closed?

**Comment by amaurymartiny** [comment]
@rootscript's answer should do the trick. Closing.

> It looks like electron needs me to set an icon image path in the BrowserWindow options to do this.

It's also possible to do now: `const mb = menubar({ browserWindow: {...} })`
