### ISSUE TITLE
how to enable the menubar app auto start at login? (mac)

### ISSUE THREAD

**Issue by calvinchankf** [maxogden/menubar#141]
Currently, I drag the app(packaged) to the dock, select 'start at login' and remove the app from the dock to enable 'start at login', but it is just a workaround and I think there should be better way to enable it.

So, can anyone help?

**Comment by akashnimare** [comment]
@calvinchankf try this https://github.com/Teamwork/node-auto-launch

**Comment by wilco3d** [comment]
+1 for node-auto-launch - worked great for me, both osx (login items) and windows (reg entry). Worth combining with electron-is-dev so you don't create them unless on distribution.

**Comment by noahbenham** [comment]
Hey @calvinchankf, did that work for you? Can this be closed?

**Comment by calvinchankf** [comment]
@noahbenham yes
