### ISSUE TITLE
Content will not be displayed

### ISSUE THREAD

**Issue by HorstMumpitz** [maxogden/menubar#15]
Hi there, 

I wanted to try menubar. For this reason I cloned this repository and followed the steps in the example directory. For some reasons the contents of index.html is not displayed. 

When starting the app I just get the following output :

    > example-menubar-app@1.0.0 start /Users/HorstMumpitz/development/javascript/menubar/example
    > electron .

    [3646:0522/095638:WARNING:dns_config_service_posix.cc(150)] dns_config has unhandled options!
    app is ready

The warning is connected to electron and a known issue. 

I'm running 10.10.3 on a Mid 2010 MacBook Pro.

**Comment by jenslind** [comment]
Yes, reported here too: https://github.com/maxogden/menubar/pull/13

You could pass in the dir option to menubar to fix this for now.
In examples main.js file:
`var mb = menubar({dir: './'})`

**Comment by HorstMumpitz** [comment]
That works perfectly. 

Thank you for the quick response.
