### ISSUE TITLE
How to access the menubar instance from code loaded from the html file

### ISSUE THREAD

**Issue by Zac-Garby** [maxogden/menubar#150]
I have my index.js which makes the menubar instance. The HTML file then loads some other scripts which do all the stuff in my app. How can I access the menubar instance from these files? I need to get the app from the menubar and quit it when a button is pressed.

**Comment by Zac-Garby** [comment]
I found a way, nevermind

**Comment by dbradleyfl** [comment]
@Zac-Garby I've been trying to figure the same thing out. Mind sharing how you did it?

**Comment by Zac-Garby** [comment]
@dbradleyfl I used inter-process communications, meaning I could send a message from my JavaScript loaded from the page to the script which actually creates the application window, telling it to quit.

**Comment by kienpham2000** [comment]
I used something like this: 

```
const app = require('electron').remote.app

function quit() {
  app.quit();
}
````

In my html, I have this:
```
<footer class="footer" onclick="quit()">
    Cmd+Q to quit
</footer>
```
