### ISSUE TITLE
Hide when clicking on other menubar item

### ISSUE THREAD

**Issue by lukasoppermann** [maxogden/menubar#155]
When the window is open and I click another item, depending on which on I click the window does not close. It happens for e.g. with Dropbox, invisionSyn, and flux. However, when clicking on googleDrive it is fine.

<img width="432" alt="screen shot 2017-01-17 at 08 27 00" src="https://cloud.githubusercontent.com/assets/813754/22011323/c027f038-dc8e-11e6-83bf-cadd102ba66b.png">

My window settings are:

```js
let options = {
  width: 350,
  height: 450,
  y: 40
}
```

**Comment by noahbenham** [comment]
Try binding to `focus-lost` and programmatically closing the menubar upon receiving the event.

**Comment by lukasoppermann** [comment]
Hey, @noahbenham 
this is not working for me. 😢 

```js
const menubar = require('menubar')
const mb = menubar(require('./app/window').options)
mb.on('focus-lost', function () {
  mb.hideWindow()
})
```

I have `alwaysOnTop: true` the event is fired and I can log something, however, the window is not closed.

**Comment by noahbenham** [comment]
@lukasoppermann Without seeing more of your project, your issue might be resolved by
1. Changing how you access the menubar instance you created. Modify line `const mb = menubar(require('./app/window').options)`
2. Hiding the window directly: `mb.window.hide()`

**Comment by lukasoppermann** [comment]
Hey @noahbenham,

the 2nd idea does not work 😞 and I don't really get wha you are trying to say with the first idea.

My options, if this is what you are referring to, are the following:

```js
let options = {
  width: 350,
  height: 450,
  tooltip: 'my app',
  index: 'file://' + process.cwd() + '/app/colors.html',
  resizable: false,
  transparent: true,
  frame: false,
  hasShadow: false,
  alwaysOnTop: true
}

module.exports = {
  createWindow: createWindow,
  options: options
}
```

However, if I just use `const mb = menubar()` it still does not work. Any other idea? Is there any more info you need that I can provide? Thanks for your help so far.

**Comment by hansott** [comment]
See https://github.com/electron/electron/issues/8689
