### ISSUE TITLE
run example failed

### ISSUE THREAD

**Issue by willin** [maxogden/menubar#157]
```
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.5/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service
 for display 5
app is ready
```

**Comment by noahbenham** [comment]
Is this after building with `electron-builder`? Regardless, this looks like an issue localized to your machine. Try logging an issue to electron or electron-builder instead.
