### ISSUE TITLE
Tray icon duplicating

### ISSUE THREAD

**Issue by jeremyroe** [maxogden/menubar#158]
I'm experiencing an issue where the tray icon is duplicating - most often 3 times.  On rare occasions many many times.  I do not know if this is specific to my app, menubar, or electron.  I've dug through issues and forums and found a few references to similar issues.  I'm happy to do further debugging and gather more information to track this down but am a bit lost on the direction to take.

This is deployed on Windows 10 and Windows 7 across about 800 computers with varying patch levels and service packs.

My code can be seen here if you wish: https://github.com/jeremyroe/it-support-app

**Comment by noahbenham** [comment]
Looks like that link to code is dead, @jeremyroe. Would be helpful to have a working example as this could be any number of things.

**Comment by jeremyroe** [comment]
Should be public now @noahbenham - sorry about the hold up

**Comment by amaurymartiny** [comment]
Is this still reproduceable? @jeremyroe the link in the first post is dead.

I'm closing it for now, please re-open if this is still a bug.
