### ISSUE TITLE
Icon 

### ISSUE THREAD

**Issue by caraquista** [maxogden/menubar#159]
Hello everyone.

My problem is as follows, when I create the menu I pass an object from it as follows:

Var mb = menubar ({
   Dir: './',
   Index: config.frontEnd.protocol + ': //' + config.frontEnd.host + ':' + config.frontEnd.port,
   Icon: process.cwd () + '/ build / img / icon.png',
   ShowDockIcon: true,
   Width: 600,
   WebPreferences: {
     NodeIntegration: false
   }

In local shows the icon perfectly.

But once I create my Mac OS executable it always shows me the image of the cat that is the default one.

How can i solve this problem??

Thank you very much in advance.

**Comment by noahbenham** [comment]
Personally, I resolve paths with `path` and `_dirname`. You'll probably want to use a png for mac and an ico for windows. For example,
```
path.join(__dirname, '../img/trayicon.ico')
```

**Comment by caraquista** [comment]
Excellent thank a lot .. work for me...
