### ISSUE TITLE
How can I listen for "window-all-closed"? My app won't quit

### ISSUE THREAD

**Issue by JoeDawson** [maxogden/menubar#163]
I'm having trouble quitting my app, I can't catch the `window-all-closed` event to quit.

None of these have worked, what should I be doing?

```
mb.on('window-all-closed', () => {
    mb.quit();
});

mb.on('window-all-closed', () => {
    mb.app.quit();
});

mb.app.on('window-all-closed', () => {
    mb.quit();
});

mb.app.on('window-all-closed', () => {
    mb.app.quit();
});
```

All windows are definitely closed, when I run the app using `electron .` from terminal it quits as I expect. But for some reason it doesn't happen after the app is built (electron-builder).

**Comment by noahbenham** [comment]
Can you bind to events on the original `app` instead of using the menubar `app`?

**Comment by JoeDawson** [comment]
Hey @noahbenham,

Would `app` be available here?

```js
'use strict';

const path = require("path");
const menubar = require('menubar');

var mb = menubar({
  y: 28,
  height: 440,
  preloadWindow: true,
  index: 'file://' + __dirname + '/app/index.html',
  icon: path.join(__dirname, 'app', 'assets', 'img', 'icons', 'trayTemplate.png'),
});

// where i'm struggling currently.
mb.on('window-all-closed', () => {
	if (process.platform != 'darwin') mb.quit();
});

mb.on('after-create-window', () => {

	mb.window.webContents.on('new-window', function(e, url) {
		e.preventDefault();
		require('electron').shell.openExternal(url);
	});

});
```

**Comment by noahbenham** [comment]
Try this instead:
```
const { app } = require('electron'); // declare at top of file

// quit entire application, not just remove menubar
app.on('window-all-closed', () => {
  if (process.platform != 'darwin') app.quit();
});
```

**Comment by JoeDawson** [comment]
Hey @noahbenham,

Still unfortunately getting the same, the window closes (then is recreated when I click the tray icon) but it doesn't quit.

Any other ideas? Appreciate your help so far.

**Comment by JoeDawson** [comment]
Here's a quick video of what I'm seeing: http://d.pr/v/gr5p

**Comment by JoeDawson** [comment]
Hmm, just revisted this. Not sure if it's because I installed a newer version of menubar, electron and electron-builder. Byour suggestion @noahbenham seemed to have fixed it. Thanks!

**Comment by noahbenham** [comment]
Ah, I was just replying as your comment popped in. Glad to hear it @JoeDawson.

**Comment by JoeDawson** [comment]
Here's my final `main.js` if anyone happens to come across this in the future.

```
'use strict';

const path = require("path");
const menubar = require('menubar');
const { app } = require('electron'); // declare at top of file

var mb = menubar({
  y: 28,
  height: 440,
  preloadWindow: true,
  index: 'file://' + __dirname + '/app/index.html',
  icon: path.join(__dirname, 'app', 'assets', 'img', 'icons', 'trayTemplate.png'),
});

app.on('window-all-closed', () => {
  app.quit();
});

mb.on('after-create-window', () => {
  mb.window.webContents.on('new-window', function(e, url) {
    e.preventDefault();
    require('electron').shell.openExternal(url);
  });
});
```

**Comment by Rajeshsparta** [comment]
Hello,

I also used this above method but it does not work for me,
Can you describe why we using menu-bar module?

**Comment by JoeDawson** [comment]
@Rajeshsparta because this is the menubar repository perhaps? :)
