### ISSUE TITLE
Is it possible to use a number instead of an icon?

### ISSUE THREAD

**Issue by dannymout** [maxogden/menubar#167]
Instead of using a icon menubar, could I use a number or text instead?

**Comment by dannymout** [comment]
No one seems to know how, I'm gonna close this.

**Comment by CodeBrauer** [comment]
A bit late but you can do this with Tray:

```
mb.tray.setImage('transparent.png');
mb.tray.setTitle('123');
```

`transparent.png` is just a 1x1 transparent PNG (you can create it with imagemagick like this: `convert -size 1x1 xc:none transparent.png`
