### ISSUE TITLE
setOption not working

### ISSUE THREAD

**Issue by miguelmota** [maxogden/menubar#171]
Setting a new icon using `setOption` has no effect

```javascript
mb.setOption('icon', 'newicon.png'); // doesn't do anything
```

**Comment by noahbenham** [comment]
Could you provide more context, @miguelmota? Are you sending a full path to the file that includes the `file://` prefix?

When're you setting this? In app.ready? After app.ready?

**Comment by miguelmota** [comment]
@noahbenham here's some sample code

```js
const menubar = require('menubar')

const mb = menubar({
   icon: 'icon.png' // works
});

mb.on('ready', function ready () {
  // later in code
  mb.setOption('icon', 'newicon.png'); // doesn't work
});
```

Is the full path required?

**Comment by noahbenham** [comment]
@miguelmota Yes, I suspect Electron is unable to resolve the path. Try passing an absolute one instead of a relative one, see [native-image documentation](https://github.com/electron/electron/blob/master/docs/api/native-image.md).

**Comment by noahbenham** [comment]
@miguelmota Is your issue resolved now? Can this issue be closed?

**Comment by miguelmota** [comment]
hmm not working after passing absolute path <code>path.resolve(`${__dirname}/icon.png`)</code>

resorted to using electron Tray

```
  const electron = require('electron');
  const Tray = electron.Tray;
  const appIcon = new Tray(iconPath);
  appIcon.setImage(iconPath);
```

@noahbenham

**Comment by amaurymartiny** [comment]
Replacing [`examples/hello-world`](https://github.com/maxogden/menubar/tree/master/examples/hello-world) with this piece of code works:

```typescript
const path = require('path');

const { menubar } = require('../../lib');

const mb = menubar();

mb.setOption('icon', path.join(__dirname, '..', '..', 'screenshot.png'));

mb.on('ready', () => {
  console.log('Menubar app is ready.');
});
```
