### ISSUE TITLE
Native menu support

### ISSUE THREAD

**Issue by rucuriousyet** [maxogden/menubar#178]
I know that electron tray apps have support for native mac menus, does this?

**Comment by majoressense** [comment]
same problem

**Comment by yceballost** [comment]
Me too with the same problem!

I would like to add a menu to add a Quit application option

Thanks!

**Comment by tslater** [comment]
Like this?

var menubar = require('menubar')
const { app, Menu, Tray } = require('electron')

const iconPath = "/path/to/icom";

app.on('ready', () => {
  let tray = new Tray(iconPath)
  const contextMenu = Menu.buildFromTemplate([
    { label: 'Item1', type: 'radio' },
    { label: 'Item2', type: 'radio' },
    { label: 'Item3', type: 'radio', checked: true },
    { label: 'Item4', type: 'radio' }
  ])
  tray.setContextMenu(contextMenu)
  var mb = menubar({
    icon: iconPath,
    tray,
  })
  mb.on('ready', function ready () {
    console.log('app is ready')
    // your app code here
  })
})

**Comment by amaurymartiny** [comment]
See https://github.com/maxogden/menubar/tree/master/examples/native-menu for an example, thanks to @tslater.

**Comment by Jip-Hop** [comment]
Is the native menu still supported? It's not working properly for me. See issue https://github.com/maxogden/menubar/issues/345.
