### ISSUE TITLE
Incorrect position when tray is on the left on Windows

### ISSUE THREAD

**Issue by seitazen** [maxogden/menubar#184]
![default](https://user-images.githubusercontent.com/6057988/29441571-d395734e-83fe-11e7-9cf5-c634175fccc1.png)

- Windows 10
- menubar 5.2.3

**Comment by julienma** [comment]
I had the same issue, and am now using https://github.com/hacdias/electron-menubar which works fine.

**Comment by julienma** [comment]
Update:

- `electron-menubar` has issues correctly handling multiple displays, which I couldn't get to fix. Instead, it was easier to fix `menubar` to correctly behave on Windows, while still behaving perfectly with multiple displays.
- I'm now using this menubar fork: https://github.com/BaguetteEngineering/menubar, based off Sidney's commit: https://github.com/sidneys/menubar/commit/233bcb8e65a8009222059e78be90ef0982c9a52d.

**Comment by amaurymartiny** [comment]
Fixed in [`menubar@6.0.4`](https://www.npmjs.com/package/menubar/v/6.0.4) 🚀
