### ISSUE TITLE
'ready', 'create-window', and 'after-create-window' events does not fire when using preloadWindow option

### ISSUE THREAD

**Issue by nicknish** [maxogden/menubar#187]
Hey y'all! Love this package, and noticed this recently:

Version: 5.2.3
CLI: See usage below
Platform: Mac OSX High Sierra 10.13.1
Stack Trace: No error

```javascript
// main.js

menubar = Menubar({
  // ...
  preloadWindow: true,
})

menubar.on('ready', () => {
  console.log('DOES IT REACH READY?')
})

menubar.on('create-window', () => {
  console.log('DOES IT REACH CREATE WINDOW?')
})

menubar.on('after-create-window', () => {
  console.log('DOES IT REACH AFTER CREATE WINDOW?')
})
```

None of these events fire when using `preloadWindow`. I _think_ this a bug. If so, I'd be more than happy to fix it.

**Comment by Ancinek** [comment]
@nicknish Did you manage to get past through that?

**Comment by amaurymartiny** [comment]
Just tried your exact snippet, it now works.

```
$ electron .
DOES IT REACH CREATE WINDOW?
DOES IT REACH AFTER CREATE WINDOW?
DOES IT REACH READY?
```

**Comment by vkolova** [comment]
I am reproducing this as well.

I started using the `ready` and `after-create-window` events in our app this morning. They worked under development, but after packaging it seemed like they are never emitted.

Removing `preloadWindow: true` resolved the issue but caused others.
