### ISSUE TITLE
Issue with icon when building

### ISSUE THREAD

**Issue by joeyorlando** [maxogden/menubar#188]
Hi there, I'm experiencing an issue which seems related to menubar searching for my tray icon. In local development things work great, but when trying to build with `electron-builder` I immediately see the below stack trace when opening the application (on OSx, have yet to test on Linux/Windows). 
```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /Volumes/Fantaztech 1.0.0/Fantaztech.app/Contents/Resources/app.asar/example/IconTemplate.png
    at App.appReady (/Volumes/Fantaztech 1.0.0/Fantaztech.app/Contents/Resources/app.asar/main_dist.js:46995:33)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

I noticed it is searching for the fallback cat icon, which I don't want, but the weird thing is that if I unarchive the built `app.asar` file, inside I do see the following file structure, showing that my images do indeed exist:
```
- main_dist.js
- main_dist.map.js
- package.json
- img/
  |_ menubar_logo.png
  |_ menubar_logo@2x.png
  |_ menubar_logo_orange.png
  |_ menubar_logo_orange@2x.png
```

`main_dist.js` is a file bundled by webpack prior to building. My `menubar` object setup goes as follows
```
electron/
  |_ utils.js
  |_ index.js

utils.js
import path from 'path';
import menubar from 'menubar';

const fp = config.environment === 'local' ? '../../img/' : 'img/'; // this is set by webpack during bundling, I've double checked that it is set to a non 'local' value when trying to build

export const icons = {
	connected: path.resolve(__dirname, `${fp}menubar_logo_orange.png`),
	disconnected: path.resolve(__dirname, `${fp}menubar_logo.png`)
};

index.js
import menubar from 'menubar';
import { icons } from './utils';

const mb = menubar({
	width: 300,
	height: 445,
	dir: __dirname,
	index: pagePaths.menubar,
	icon: icons.disconnected,
	resize: false,
	alwaysOnTop: true,
	preloadWindow: true
});
```

**Comment by paulius005** [comment]
@joeyorlando did you ever figure this out? Im having the same issue

**Comment by paulius005** [comment]
Figured it out, I was compiling my `main.js` file with webpack && babel

had to add this to my webpack config to get my icon dir to be properly calculated:
```
  target: 'electron-main',
  // this is necessary to get __dirname && __filename to work properly in the
  // main script
  // https://github.com/webpack/webpack/issues/1599#issuecomment-186841345
  node:   {
    __dirname:  false,
    __filename: false
  }
```

**Comment by sean7218** [comment]
do you have to add webpack.config.js ? how exactly did you solve it?

**Comment by paulius005** [comment]
yep, I have mulitple webpack files that I use for main vs renderer
