### ISSUE TITLE
Window appears at bottom when taskbar is on top (on Windows)

### ISSUE THREAD

**Issue by jasonlong** [maxogden/menubar#189]
A user reported an issue for my project showing the app window rendering at the bottom of the window even though their Windows taskbar is on the top. 

![unnamed](https://user-images.githubusercontent.com/6104/37284307-6d3aa0cc-25d1-11e8-9ae3-d0f0070d6e6a.png)

Is this something menubar handles already and I'm missing a setting?

**Comment by quietshu** [comment]
Same issue today. I'm trying to find a workaround (https://github.com/inns/mak-mini/issues/3).

**Comment by amaurymartiny** [comment]
Fixed in [`menubar@6.0.4`](https://www.npmjs.com/package/menubar/v/6.0.4) 🚀  (via PR #217)
