### ISSUE TITLE
Menu always opens on active display on OSX

### ISSUE THREAD

**Issue by russellhaering** [maxogden/menubar#19]
On OSX (10.10.3) with two displays, the menu always opens on whichever display has the focused window at the time the icon is clicked, regardless of which display the click happens on.

**Comment by maxogden** [comment]
I don't have another monitor to test on, but if someone can figure out how to fix this then patch welcome :)

**Comment by russellhaering** [comment]
Turns out this is an issue in Electron: https://github.com/atom/electron/issues/1847

I submitted a PR with a workaround, although I don't especially love it.

**Comment by fabien-d** [comment]
Resolved with the release of 2.0.17
