### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [maxogden/menubar#200]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by maxogden** [comment]
I'm not maintaining it any more, if someone wants to take it over send me an email

**Comment by slackmage** [comment]
Max I'm currently upgrading it. Would be happy to.

**Comment by johndatserakis** [comment]
This library is being use in a ton of projects - hope we get someone on to maintain it a bit.

**Comment by amaurymartiny** [comment]
For those interested, I created a fork here:

https://github.com/amaurymartiny/menubar/

### Highlights:
- Codebase converted to TypeScript, so typings come for free.
- Merged PRs 142, 151, 192, 193, 194, 198.
- Started to add tests
- Improve workflow: use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/), use semver, add a CHANGELOG.
- Overall I'm pretty active on Github (check my profile), so issues won't stay unanswered. I'm also using menubar in 2 of my projects (one personal and one professional).

The first version of this fork has been released on npm: [`@amaurymartiny/menubar@6.0.0`](https://www.npmjs.com/package/@amaurymartiny/menubar).

**Comment by mischah** [comment]
@amaurymartiny 

Why did you fork it? 

To quote @maxogden:
> I'm not maintaining it any more, if someone wants to take it over send me an email

Wouldn’t it make more sense that @maxogden adds you as contributor with admin rights and and add you to <https://www.npmjs.com/package/menubar> as well?

You can move it to https://github.com/amaurymartiny/menubar/ later.

_These are just my 5 cents. 😘_

**Comment by amaurymartiny** [comment]
@mischah Sure. But I sent him an email, pinged him on twitter, and mentioned him a couple of times on github. No answer.

I'm forking to have some work done.

**Comment by mischah** [comment]
Makes totally sense. Thanks for the feedback.

**Comment by pakastin** [comment]
@maxogden could you add @amaurymartiny as admin?

**Comment by maxogden** [comment]
Sorry for the delay. I added @amaurymartiny on github and npm, and slackmage on github (not sure what their npm account is)
