### ISSUE TITLE
Using menubar prevents all other application windows of exiting maximized state on MacOS

### ISSUE THREAD

**Issue by vkolova** [maxogden/menubar#215]
**Version**: 6.0.3
**OS**: macOS Mojave 10.14.5 (but reproducible on Sierra as well)

It came to my attention that our application could not exit maximized windows. After some poking around and testing with a clean electron project, I came to the realization that it was the usage of menubar that's breaking things.

Steps:
* Start application
* Click the maximize button on the main window
* Try to exit. You'll see that the frame does not appear on the top of the screen

Reproducible with the minimal menubar setup.

[Demo repository](https://github.com/vkolova/electron-mac-os-issues)

(Note: I set up the demo to use one index.html for the main and menubar windows, in reality there's no difference if two different html files are used.)

**Comment by amaurymartiny** [comment]
Confirmed. I will investigate a bit.

**Comment by vkolova** [comment]
@amaurymartiny Any progress on this? I tried to investigate myself, but I did not find anything suspicious.

**Comment by YAtOff** [comment]
This happens when the dock is hidden.
Running `app.dock.hide()` on any Electron app will make that happen.
Creating a `menubar` with `showDockIcon: true` will fix the issue, but with an icon in the dock.
