### ISSUE TITLE
Export getWindowPosition() and taskbarLocation()?

### ISSUE THREAD

**Issue by julienma** [maxogden/menubar#224]
Hey, would it be possible to export `getWindowPosition` and `taskbarLocation` from [`/src/util/getWindowPosition`](https://github.com/maxogden/menubar/blob/master/src/util/getWindowPosition.ts#L37)?

I already use that same code in my app, and it'd be great if I could just source these functions from menubar instead of keeping them in my code.

Specifically, I use the equivalent of `taskbarLocation` when resizing height dynamically: by default, macOS auto-limits app height to actual screen height, so there's no issue. However, Windows doesn't limit it, so I need to force a max height (Note: this was true as of 1 year ago, using Electron 1.8.4 — maybe things have changes with Electron 5?).
To do that, I need to know where the taskbar is, so I know if I should expand my app's window from top or from bottom of the screen.

**Comment by amaurymartiny** [comment]
Fixed in [`menubar@6.0.5`](https://www.npmjs.com/package/menubar/v/6.0.5) 🚀
