### ISSUE TITLE
Text in menubar rather than icon

### ISSUE THREAD

**Issue by jsifalda** [maxogden/menubar#23]
Is there way how to display text in menu bar instead of icon? 
For example if I want to use it as a countdown? (changing text every minute?)

**Comment by jenslind** [comment]
I don't think Electron supports this.
See https://github.com/atom/electron/issues/1553

**Comment by jsifalda** [comment]
such a pity :(

**Comment by davej** [comment]
You could probably create the icon on the fly using canvas and output the icon to png, `canvas.toDataURL("image/png")`.

**Comment by vitorgalvao** [comment]
This is indeed supported by Electron. Perhaps not on Linux and Windows, but definitely on OS X. [kyoku](https://github.com/cheeaun/kyoku) does it to show the currently playing song from iTunes.

**Comment by willwashburn** [comment]
As @vitorgalvao  noted, in OSX at least you should be able to set the title of the electron Tray instance:
http://electron.atom.io/docs/v0.36.8/api/tray/#traysettitletitle-os-x

For instance

```
mb.on('ready', function ready () {
  mb.tray.setTitle('woo!')
})
```
