### ISSUE TITLE
Communication between App and Menubar's BrowserWindow

### ISSUE THREAD

**Issue by gregmax17** [maxogden/menubar#230]
Just wondering if there is a working example on how to communicate between the app and browser window.

I have looked into ipcMain and ipcRenderer, however in my `index.html` I would get the error:

```
Uncaught ReferenceError: require is not defined
    at index.html:26
```

Something else I need to do to setup in order to get ipcMain and ipcRenderer to work?

**Comment by amaurymartiny** [comment]
In Electron 5 `nodeIntegration` is false by default, for security reasons.

Try `menubar({ browserWindow: { nodeIntegration: true });`, but bear in mind it's insecure.

**Comment by MalayaliRobz** [comment]
in Electron 10 it's like 
```
menubar({
  browserWindow: {
    webPreferences: {
      nodeIntegration: true
    }
  }),
```
