### ISSUE TITLE
Using setOption() doesn't work when providing an option in an object

### ISSUE THREAD

**Issue by blakewilson** [maxogden/menubar#236]
[//]: # "Hey there and thank you for using Menubar's issue tracker!"
[//]: # "Please fill in these information to describe your issue."

### Description
Hi there! I'm trying to dynamically change the width/height of the menubar through `setOption()`, however, since it's a key in the `browserWindow` object I don't think I can access it. I tried using the key `browserWindow.width` but that doesn't seem to work since it's a string of course. Is there a possible way to do this, or a work around?

### Steps to Reproduce the Problem

This:
```javascript
console.log(mb.setOption('browserWindow.width', 500))
```

Will result in `undefined`

### Expected Behaviour
Should set the `browserWindow` object's `width` key.

### Actual Behaviour

Does not set the `browserWindow` object's `width` key.

### Specifications

- Menubar version: 6.0.6
- Platform: MacOS 10.14.5
- Electron version: 5.0.6

Thanks for all your hard work!

**Comment by blakewilson** [comment]
After taking a look at the source [here](https://github.com/maxogden/menubar/blob/master/src/Menubar.ts#L114), it looks like `setOption()` takes the first argument and will simply add it to the main options object as a new key. It will not look to determine if the first argument is trying to reference a nested object.

As a result, I simply edited the options directly using the following code:
```javascript
mb._options.browserWindow.height = 500
```

**Comment by amaurymartiny** [comment]
Yes, some small notes:
- `mb.window` is a shortcut for `mb._options.browserWindow` (which btw won't work in TS because `options` is a private member)
- I would recommend to use browserWindos.setSize() [docs here](https://electronjs.org/docs/api/browser-window#winsetsizewidth-height-animate) which seems like the official way to resize

So all in all: `mb.window.setSize(width, height)`
