### ISSUE TITLE
Dynamically changing icon?

### ISSUE THREAD

**Issue by a9io** [maxogden/menubar#24]
It would be lovely to see a method which loads a different icon on demand.

Something like `mb.set("icon", "icon_active.icns", function(){console.log("icon changed")})` maybe?

You can see this behavior being implemented in gitify [here](https://github.com/ekonstantinidis/gitify/blob/master/main.js#L89).

**Comment by davej** [comment]
Is this different from `mb.tray.setImage('icon_active.png')`?

**Comment by a9io** [comment]
Oh I didn't realize the `tray` object was inherited. You're probably right, thanks.
