### ISSUE TITLE
Arrow popover menubar shows unwanted shadow/outline on Mac OS X

### ISSUE THREAD

**Issue by athenawisdoms** [maxogden/menubar#241]
### Description

Strange shadows/outline are seen on the top of the arrow popover menubar on Mac OS X.

### Steps to Reproduce the Problem

Run the [arrow popover menubar example](https://github.com/maxogden/menubar/tree/master/examples/arrow) on Mac OS X Mojave 10.14.5.

**main.js**

```
const { menubar } = require('menubar')

const mb = menubar({
  browserWindow: { transparent: true }
});

mb.on('ready', () => {
  console.log('Menubar app is ready.');
});
```

**index.html**

```
<html>
  <head>
    <title>Example App</title>
    <link rel="stylesheet" href="index.css" />
  </head>
  <body class="myarrow">
    <div class="page">Hello World.</div>
  </body>
</html>
```

**index.css**

```
.myarrow {
    position: relative;
    padding: 12px 0;
  }
  
  .myarrow:before {
    content: '';
    height: 0;
    width: 0;
    border-width: 0 8px 12px 8px;
    border-style: solid;
    border-color: transparent transparent #eeeeee transparent;
    position: absolute;
    top: 0px;
    left: 50%;
    transform: translateX(-50%);
  }
  
  .page {
    background: #eeeeee;
    width: 340px;
    height: 500px;
    margin: 0 auto;
  }
  
  .darwin.page {
    border-radius: 5px;
    overflow: hidden;
  }
```

### Expected Behaviour

No white outline/shadow above the arrow popover menubar.

![image](https://user-images.githubusercontent.com/6615285/62175308-3b27ff80-b30b-11e9-9bd1-cce46475e6b7.png)

### Actual Behaviour

Observed white outline/shadow above the arrow popover menubar.

![image](https://user-images.githubusercontent.com/6615285/62175377-817d5e80-b30b-11e9-8e8a-f90f700f22f7.png)

### Specifications

- Menubar version: 6.0.6
- Platform: Mac OS X Mojave 10.14.5
- Electron version: 6.0.0

**Comment by amaurymartiny** [comment]
Hi @athenawisdoms, thanks for the report. This is a known issue, it's a bug with Mojave. Have a look at https://github.com/electron/electron/issues/13164, there are also some hacky workarounds.
