### ISSUE TITLE
How to use IPC from inside menubar page?

### ISSUE THREAD

**Issue by umaxfun** [maxogden/menubar#244]
Hi guys,

Trying to use IPC from inside menubar window, and no luck, semes that nothing from electron exists in that context. I searched the web page's js context for 'require', 'electron', 'ipc*' with no luck.

How to use IPC from inside menubar page?

**Comment by umaxfun** [comment]
Nevermind, I've found the solution.

**Comment by umaxfun** [comment]
Just kidding 😸 
The solution was: 
```js
const mb = menubar({webPreferences: {nodeIntegration: true}});
```

**Comment by huang-ju** [comment]
Thank you
