### ISSUE TITLE
Conditionally open browserWindow when clicking icon

### ISSUE THREAD

**Issue by softwheredon** [maxogden/menubar#253]
Hello,

Is it possible to open a different browserWindow (e.g. loginBrowserWindow) when tray is clicked and a certain condition is not met (token set). 

Currently I am using the 'after-show' event to see if token is set and quickly hide the main window.

If im not mistaken, replacing the window with loadURL() doesn't allow for having different browser options. In my case one view shows title bar and the other doesn't.

**Comment by amaurymartiny** [comment]
I am not sure what you are trying to achieve. `menubar` is just a utility to show a browserWindow on tray icon click, you can put whatever content in that browserWindow.

Can you explain a little bit more?

**Comment by softwheredon** [comment]
Thanks for your response. I'll try to explain myself better.

My main window should only be accessible to authenticated users. I have a separate BrowserWindow where users can login, after logging in I set their api token.

When the menu bar icon is clicked, but users are not logged in. I do not want the main window to be shown, I just want to toggle the display of the login view.

So basically when users click the tray icon and no api token is set I want to display BrowserWindow2 and when users click the icon and the tray icon is set I want to show BrowserWindow1.

**Comment by amaurymartiny** [comment]
Why don't you check this logic in the JS code of the renderer of one browserWindow.

For example, with React, in the main browserWindow, you'd do:

```jsx
render() {
  return isTokenPresent ? <AuthicatedDashboard /> : <LoginPage />
}
```

If you really need 2 browserWindows, then `menubar` will not cater for this use case, you might need to use Electron Tray (https://electronjs.org/docs/api/tray) directly

**Comment by softwheredon** [comment]
Thanks. I decided to use tray directly.
