### ISSUE TITLE
Windows icon template

### ISSUE THREAD

**Issue by rwwagner90** [maxogden/menubar#258]
On Mac, we are able to use `iconTemplate` and it will change to either black or white based on if the user is in dark or light mode. How can we do something similar with Windows and/or use a different icon in Windows entirely?

**Comment by rwwagner90** [comment]
@maxogden any ideas?

**Comment by amaurymartiny** [comment]
This is only supported in macOS. https://github.com/electron/electron/blob/master/docs/api/native-image.md#template-image

> use a different icon in Windows entirely?

This should be fairly easy:
```tsx
menubar({
  icon: process.platform === 'win32' ? 'icon1' : 'icon2'
});
```

**Comment by rwwagner90** [comment]
I can confirm this works, and if you use a `.ico`file it will adjust size accordingly.
