### ISSUE TITLE
Configurable window.on('blur') behaviour

### ISSUE THREAD

**Issue by masom** [maxogden/menubar#26]
BrowserWindow supports the `always-on-top` option but menubar calls `hideWindow` when focus is lost.

This behaviour makes it kinda hard to use the built-in developer tools.

**Comment by fabien-d** [comment]
Closing. Fixed with https://github.com/maxogden/menubar/pull/27.

> we can always add fancier stuff in the future if people end up needing it https://github.com/maxogden/menubar/pull/27#issuecomment-113281702
