### ISSUE TITLE
Feature request: options to pass to window.loadUrl / userAgent option

### ISSUE THREAD

**Issue by adam-lynch** [maxogden/menubar#262]
[//]: # "Hey there and thank you for using Menubar's issue tracker!"
[//]: # "Please fill in these information to describe your issue."

Electron now gives a deprecation warning if you call `browserWindow.webContens.setUserAgent` instead of passing the `userAgent` property to `browserWindow.loadUrl`. This isn't possible right now, so maybe there should be a `userAgent` option or the ability to give an object which is passed to `.loadUrl` (along with the value of the `index` option).

If that sounds good, I could submit a PR? It seems straight-forward enough.

### Specifications

- Menubar version: 7.1.0
- Platform: Mac OS 10.15.2
- Electron version: 7.1.8

**Comment by amaurymartiny** [comment]
Yes, this sounds good, go ahead with a PR.

>  or the ability to give an object which is passed to .loadUrl

I'd do exactly like this

**Comment by adam-lynch** [comment]
https://github.com/maxogden/menubar/pull/263

**Comment by amaurymartiny** [comment]
Published in [menubar@7.2.0](https://www.npmjs.com/package/menubar/v/7.2.0) 🚀

**Comment by adam-lynch** [comment]
Heads up in case anyone comes across this in future, you can also set your user agent globally with Electron. See [app.userAgentFallback](https://www.electronjs.org/docs/api/app#appuseragentfallback). I.e. all windows and webContents will use that user agent, you won't have to specify it each time. Especially handy when Electron itself is creating a new window when the webContents' `new-window` event happens. 

This isn't strictly the same as the feature we've just added, but it's worth noting.
