### ISSUE TITLE
How do I setup live-reload or watch?

### ISSUE THREAD

**Issue by samholmes** [maxogden/menubar#271]

**Comment by amaurymartiny** [comment]
Do you mean:
1. how to setup live-reload in this repo, so that you can modify this repo's code and see changes on ctrl+s?
2. how to setup live-reload in your own project which uses the `menubar` package from npm?

**Comment by samholmes** [comment]
> Do you mean:
> 
> 1. how to setup live-reload in this repo, so that you can modify this repo's code and see changes on ctrl+s?
> 2. how to setup live-reload in your own project which uses the `menubar` package from npm?

#2

I would like to have a good dev setup where I can make changes to source code, save, then see updates immediately.

**Comment by amaurymartiny** [comment]
This is out of scope of this repo. I suggest having a look at online tutorials, there are several alternatives, some of them outlined in https://stackoverflow.com/questions/45622125/how-can-i-add-live-reload-to-my-nodejs-server.
