### ISSUE TITLE
macOS: Control + click doesn't trigger right click

### ISSUE THREAD

**Issue by philippkuehn** [maxogden/menubar#275]
### Description

Usually `control + click` triggers a right click on macOS. This is not working for this menubar.

### Steps to Reproduce the Problem

1. `control + click` on menubar

### Expected Behaviour

Menubar menu opens.

### Actual Behaviour

Nothing happens.

### Specifications

- Menubar version: 8.0.1
- Platform: macOS
- Electron version: 8.0.0

**Comment by philippkuehn** [comment]
sorry. i see that this is not related to this package. it's related to electron.

**Comment by amaurymartiny** [comment]
Would you mind posting the link to the Electron issue?
