### ISSUE TITLE
Should the dock icon open the app?

### ISSUE THREAD

**Issue by rwwagner90** [maxogden/menubar#278]
We have the `showDockIcon` option, but it seems clicking the dock icon does not show the app. Should it should the app or is the icon solely to show it is running? I would love to be able to open the app from the dock icon and have the window show.

**Comment by amaurymartiny** [comment]
True, right now it only shows the dock icon. If someone makes a PR for this, I can merge it

**Comment by rwwagner90** [comment]
@amaurymartiny would something like this work?

```js
mb.app.on('activate', (event, hasVisibleWindows) => {
  if (!hasVisibleWindows) {
    mb.showWindow();
  } else {
    mb.hideWindow();
  }
});
```

I added that in my app and it seems to work okay so far.

**Comment by amaurymartiny** [comment]
On macos, I just tried 5-6 apps, if you click on the dock icon when the app is already opened, it doesn't hide it. So I would remove the hideWindow part

**Comment by rwwagner90** [comment]
@amaurymartiny PR is up, hope I did it right! https://github.com/maxogden/menubar/pull/279
