### ISSUE TITLE
Use menubar without displaying a window, just to trigger an action on the click of the icon in system tray

### ISSUE THREAD

**Issue by dobl1** [maxogden/menubar#285]
### Description
Question, how cqn I use menubar without displaying a window, just to trigger an action on the click of the icon in system tray ?

My need is to have just à click action on the system tray icon.

I have tried to hide the window using option `"browserWindow": { width: 0, height: 0 }` or setting the background transparent. But not working.

Is it possible and best do you have example ?

Thanks !

**Comment by amaurymartiny** [comment]
Menubar itself is quite simple, it's basically:
- one Electron Tray item
- one Electron BrowserWindow item
- some glue code to make them behave well together

If you don't need a BrowserWindow, then probably the easiest is just to use the Tray directly, without menubar: https://www.electronjs.org/docs/api/tray.

I hope that answers your question.
