### ISSUE TITLE
Built application's javascript doesn't run?

### ISSUE THREAD

**Issue by a9io** [maxogden/menubar#29]
Hello, [my application](https://github.com/a9io/alienbox) runs perfectly fine when run with `electron index.js`, but when I try to build it with `electron-packager`, the resulting binary's javascript isn't willing to run.

The window and index.html/css load fine, but the javascript clearly isn't running based on the behavior of the templates, button clicks, and icon changes. You can observe that the default "cat" icon is still there when I configured it with a custom icon. Every other configuration property when the menubar constructor is initialized runs fine.

The build's resources contain all necessary files, I even ran `electron index.js` inside the resources and it worked great. I think there is something fishy that happens when the application is run as a binary...

Could anyone help me out? This is clearly abnormal and I can't seem to figure out the solution.

**Comment by maxogden** [comment]
add this to your app:

```
mb.once('show', function () {
  mb.window.openDevTools();
})
```

which lets you see the error, which is that you get an EACCESS error when the `node-persist` module tries to `mkdir /persist`. I think this is because `process.cwd()` is set to `/` in electron ([mentioned here](https://github.com/atom/electron/issues/1712)).

You should be able to fix it by passing `process.resourcesPath + '/persist'` as the dir

**Comment by a9io** [comment]
Thanks. Not that I have anything against cats, but it seems I can't change the icon in the `config` object, neither can I change it using the `tray`'s  setImage() function, even when concatenating: `process.resourcesPath + "/icons/inbox.png"`. For the latter, there are some nasty-looking eventEmitter argument errors that are thrown.

**Comment by a9io** [comment]
Nevermind, had to do `__dirname` and it worked fine (forgot preceding `/`). Thanks!
