### ISSUE TITLE
drag/drop item to menubar event?

### ISSUE THREAD

**Issue by niftylettuce** [maxogden/menubar#3]

**Comment by maxogden** [comment]
I have no idea, I'd ask here https://github.com/atom/atom-shell/issues as it would need to be doable on mac, linux, windows for it to make it into atom-shell

**Comment by diasdavid** [comment]
This would be so great! Any recent developments that would enable it?

**Comment by diasdavid** [comment]
Trying to listen to `drop-files` event on `menubar.tray` but it never fires. Not sure what I'm missing, investigating :) 

https://github.com/atom/electron/blob/master/docs/api/tray.md#event-right-clicked

**Comment by diasdavid** [comment]
Nevermind, I was using a older version of electron :) works now! :)
