### ISSUE TITLE
problem with default path (feedback welcome)

### ISSUE THREAD

**Issue by maxogden** [maxogden/menubar#30]
I think its related to this change https://github.com/maxogden/menubar/commit/ee03191ec0b275a46a46dc6302e3a3e8c6b1fba4 which was caused by me opening this issue https://github.com/atom/electron/issues/1712 which recommended using `process.resourcesPath`, which [according to this](https://github.com/atom/electron/blob/cd0aa4a956cb7a13cbe0e12029e6156c3e892924/docs/api/process.md#process-object) returns the 'Path to JavaScript source code'.

However, I think now this is incorrect. When running a menubar app from the CLI via e.g. `electron .`, `process.resourcesPath` will be `/path/to/electron-prebuilt/dist/Electron.app/Contents/Resources`, but what you really want it to be is `/path/to/my/app/source/code`.

Anyone have thoughts on what the default src path should be? It can't be `__dirname` since that will be inside the `node_modules/menubar` folder.

**Comment by maxogden** [comment]
I also just opened an issue to get clarification on Electron https://github.com/atom/electron/issues/2108

**Comment by jenslind** [comment]
Looks like `app.getAppPath()` has been implemented now (not released yet).

https://github.com/atom/electron/issues/2127

**Comment by maxogden** [comment]
woot

**Comment by tony-garcia** [comment]
maybe I'm not understanding what getAppPath() is supposed to do. From this thread, @maxogden requested something that will give `/path/to/my/app/source/code`. However, what I'm getting with app.getAppPath() is `/path/to/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar`, which is kind of useless.
