### ISSUE TITLE
Plan to support Electron 12

### ISSUE THREAD

**Issue by trungutt** [maxogden/menubar#331]
[//]: # "Hey there and thank you for using Menubar's issue tracker!"
[//]: # "Please fill in these information to describe your issue."

### Description
When I did `npm install menubar`, I got

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-project@3.3.2
npm ERR! Found: electron@12.0.6
npm ERR! node_modules/electron
npm ERR!   dev electron@"^12.0.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer electron@"^9.0.0 || ^10.0.0 || ^11.0.0" from menubar@9.0.3
npm ERR! node_modules/menubar
npm ERR!   menubar@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
### Steps to Reproduce the Problem

1. Setup a dummy project with Electron 12. Or get an existing one, for example https://github.com/vercel/hyper
2. `npm install menubar`

### Expected Behaviour
Electron 12 should be supported

### Actual Behaviour
Electron 12 isn't supported

### Specifications

- Menubar version: 9.0.3
- Platform: darwin (Bigsur)
- Electron version: (Run `electron -v` or `node_modules/.bin/electron -v` to get it) 12.0.5

### Other information
Should it be a matter of changing https://github.com/maxogden/menubar/blob/2a187abe8923bb857f29787bb5b73310374964a9/package.json#L61 ?

**Comment by amaurym** [comment]
It's in 9.0.4 🚀

**Comment by StefanScherer** [comment]
Thank you @amaurym for the super fast response  and new release!

**Comment by trungutt** [comment]
Thank you @amaurym for your great reactivity!
