### ISSUE TITLE
How to require node modules?

### ISSUE THREAD

**Issue by dyaskur** [maxogden/menubar#334]
[//]: # "Hey there and thank you for using Menubar's issue tracker!"
[//]: # "Please fill in these information to describe your issue."

### Description
I want to use npm modules on menubar window.
my html/JS is working fine when using `BrowserWindow`, but why can't work using `menubar`?  it's return require is not defined

### Steps to Reproduce the Problem

1. add JS on the HTML that use require from node_modules
2. my require code is: `const uuidv4 = require('uuid/v4');`
### Expected Behaviour
can require module from node_modules
### Actual Behaviour
cant, return `ReferenceError: require is not defined`. 
### Specifications

- Menubar version: latest
- Platform: MacOS
- Electron version:  9.4.4

**Comment by dyaskur** [comment]
I tried below code:

```
app.on('ready', function () {

    // Create the browser window.
    browserWindow = new BrowserWindow(
        {
            webPreferences: {
                nodeIntegration: true
            }
        });

    const mb = menubar({
       browserWindow
    })

    mb.on('ready', () => {
        console.log('app is ready');
        mb.showWindow();

        // your app code here
    });
}
```)

but still doesnt work, and return 1 blank window, and 1 menubar window. 

Maybe this is my stupidity, but I will appreciate if someone help me.

**Comment by dyaskur** [comment]
OMG, it's my fault because I use window instance instead of BrowserWindowConstructorOptions . How stupid am I. 

By the way , the link on the documentation is wrong, May I fix it?

https://github.com/maxogden/menubar/blob/master/docs/interfaces/_types_.options.md#index

**Comment by amaurym** [comment]
Thanks! Since this is solved, i'll close the issue.
