### ISSUE TITLE
Plan to support Electron 13

### ISSUE THREAD

**Issue by trungutt** [maxogden/menubar#344]
[//]: # "Hey there and thank you for using Menubar's issue tracker!"
[//]: # "Please fill in these information to describe your issue."

### Description
When I did npm install menubar, I got

```
npm WARN menubar@9.0.4 requires a peer of electron@^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 but none is installed. You must install peer dependencies yourself.
```

### Steps to Reproduce the Problem

1. Setup a dummy project with Electron 13. Or get an existing one, for example https://github.com/vercel/hyper
2. `npm install menubar`

### Expected Behaviour
No warning comes out during `npm install`

### Actual Behaviour
Electron 13 isn't really taken into account during `npm install`

### Specifications

- Menubar version: 9.0.4
- Platform: darwin (Bigsur)
- Electron version: (Run `electron -v` or `node_modules/.bin/electron -v` to get it) 13.1.4

### Other information
Should it be a matter of changing https://github.com/maxogden/menubar/blob/3230118eab3524381c542f7c6e06dfd1a9183793/package.json#L61 ?

**Comment by amaurym** [comment]
> Should it be a matter of changing 

Yes, would you like to open a PR?
