### ISSUE TITLE
undefined error when clicking on the menubar icon

### ISSUE THREAD

**Issue by vanntastic** [maxogden/menubar#35]
Hi!

I just checked out your repo and attempted to run the app from the example directory, it looked like the app booted up, but there was an error that popped up when I clicked on the icon in the menubar - screenshot attached.

![screenshot_7_16_15__12_55_pm](https://cloud.githubusercontent.com/assets/9515/8731259/adf16e60-2bbb-11e5-9267-311f4c503256.jpg)

**Comment by jenslind** [comment]
What version of electron are you using? And on what OS?

**Comment by vanntastic** [comment]
I was using electron 0.25.1 on OSX 10.10.4 , just upgraded to electron 0.30.0 and everything seems to work fine now - thanks for the followup!
