### ISSUE TITLE
Does this work with electron-context-menu

### ISSUE THREAD

**Issue by nhayfield** [maxogden/menubar#354]
Trying to use both electron-context-menu and menubar in the same app but can't seem to get them to work. 
I would have figured i could pass the menubar.window into the contextmenu and have it work but it does not for some reason. 
Anyone else ran into this?

**Comment by nhayfield** [comment]
` menuBar.app.on('web-contents-created', () => {
      contextMenu();
    });`

sad to say it took me hours to figure this out but it does work

**Comment by linonetwo** [comment]
Okay, I just put it in `menuBar.on('ready'` and it worked for me.
