### ISSUE TITLE
Name Conflict on TypeScript

### ISSUE THREAD

**Issue by rhysd** [maxogden/menubar#37]
Hi.

I'm using menubar in TypeScript and found an issue.

When I import `menubar` as below,

``` typescript
// Definition in lib.d.ts
declare module "menubar" {
    function create(opts: Object): any;
    export = create;
}

// ...

// main.ts
import * as menu from 'menubar';
```

I got an error

```
browser/main.ts(3,23): error TS2497: Module '"menubar"' resolves to a non-module entity and cannot be imported using this construct.
```

It seems that `menubar` is already defined in [TypeScript standard lib.d.ts](https://github.com/Microsoft/TypeScript/blob/a24aa6f57d281bafd3535f0f4c3f492364a8b4d6/bin/lib.d.ts#L16369).  It is defined as global variable and leads to above error.

Is there any way to solve this problem?
Now I avoid this issue in dirty way but it disables type check for whole `menubar` module

``` typescript
// Now using JS style require...
var menu = require('menubar');
```

**Comment by maxogden** [comment]
hmm I actually have no idea sorry, but feel free to leave this issue open
in case someone else does

On Thursday, July 23, 2015, Linda_pp <notifications@github.com> wrote:

> Hi.
>
> I'm using menubar in TypeScript and found an issue.
>
> When I import menubar as below,
>
> // Definition in lib.d.tsdeclare module "menubar" {
>     function create(opts: Object): any;
>     export = create;
> }
> // ...
> // main.tsimport * as menu from 'menubar';
>
> I got an error
>
> browser/main.ts(3,23): error TS2497: Module '"menubar"' resolves to a non-module entity and cannot be imported using this construct.
>
> It seems that menubar is already defined in TypeScript standard lib.d.ts
> <https://github.com/Microsoft/TypeScript/blob/a24aa6f57d281bafd3535f0f4c3f492364a8b4d6/bin/lib.d.ts#L16369>.
> It is defined as global variable and leads to above error.
>
> Is there any way to resolve this problem?
> Now I avoid this issue in dirty way but it disables type check for whole
> menubar module
>
> // Now using JS style require...var menu = require('menubar');
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxogden/menubar/issues/37>.
>


-- 
Sent from my phone

**Comment by rhysd** [comment]
@maxogden 

Thanks.  I'll do that.

I write the current workaround for me.

I defined the `menubar` object as below.

```typescript
declare class MenuBar implements NodeJS.EventEmitter {
    on(event: string, listener: Function): MenuBar;
    once(event: string, listener: Function): MenuBar;
    removeListener(event: string, listener: Function): MenuBar;
    removeAllListeners(event?: string): MenuBar;
    setMaxListeners(n: number): void;
    listeners(event: string): Function[];
    emit(event: string, ...args: any[]): boolean;

    addListener(event: string, listener: Function): MenuBar;
    tray: GitHubElectron.Tray;
    app: GitHubElectron.App;
    window: GitHubElectron.BrowserWindow;
}
```

And I use it for the returned value from `create()` as below.

```typescript
var mainMenu: MenuBar = require('menubar')(menuConfig);
```

This is better than the workaround I showed previously because now `mainMenu` has a type.

**Comment by amaurymartiny** [comment]
Menubar has since been rewritten into TS. Typings come for free.
