### ISSUE TITLE
Support for inverted menu bar icons when using dark style OS X

### ISSUE THREAD

**Issue by johanbrook** [maxogden/menubar#38]
Hi! Great tool.

It would be neat if this can support dynamic switching between regular and inverted menu bar icons for OS X, when using dark style menu bar. Right now, there is only support for one type – regular or inverted – not both, which makes regular, dark icons invisible when using dark OS X.

**Comment by johanbrook** [comment]
This doesn't even seem to be supported down in Electron's `Tray` class -.- https://github.com/atom/electron/blob/master/docs/api/tray.md

**Comment by jenslind** [comment]
https://github.com/atom/electron/blob/master/docs/api/native-image.md#template-image

**Comment by johanbrook** [comment]
Nice, thanks, @jenslind. I need to learn 2 read.

**Comment by pie6k** [comment]
Note:

Remember to put `Template` at the end of icon file eg name it `MenuIconTemplate.png` instead of `MenuIcon.png` (https://github.com/electron/electron/blob/master/docs/api/native-image.md#template-image)
