### ISSUE TITLE
Window behaviour buggy when used with multiple retina and non-retina displays

### ISSUE THREAD

**Issue by davej** [maxogden/menubar#39]
To recreate this on OS X, you need a retina Macbook connected with a standard DPI external monitor:

1. Launch menubar app on monitor 1 and click to open the menubar window.
2. Close the menubar window
3. Open the menubar window on monitor 2.

If monitor 1 is retina and monitor 2 isn't then the width and height of the window will be halved, see screenshot below.

If monitor 1 is standard dpi (non-retina) and monitor 2 is retina then the window will be downscaled to the standard resolution (72dpi).

![screen shot 2015-07-29 at 19 09 25](https://cloud.githubusercontent.com/assets/26971/8965980/9ecc89d6-3626-11e5-8a5f-1dfb9f5174d7.png)

I haven't investigated this properly yet but my hunch is that this could be an upstream bug in Electron (or possibly Chromium). I can create an issue there instead if that is the case.

**Comment by maxogden** [comment]
Hmm I'm on a lowly non-retina macbook, but perhaps someone else can reproduce and dig in :)

**Comment by jenslind** [comment]
I can confirm this.

**Comment by fabien-d** [comment]
I can also confirm this. We've been trying to find the root cause and haven't been able to. All logged `coords` come back with the proper values which [seems to] point to a Chromium bug.

**Comment by jenslind** [comment]
Yeah, looks like an upstream issue.

**Comment by davej** [comment]
Perhaps @zcbenz might have some further insight?

**Comment by maxogden** [comment]
Rather than bug one maintainer of Electron here we should open an issue in the appropriate place so it can be triaged by all contributors

**Comment by davej** [comment]
I agree, I'm just not sure where the appropriate place is.

**Comment by muan** [comment]
> I'm just not sure where the appropriate place is.

I think that'd be https://github.com/atom/electron.

**Comment by davej** [comment]
Tested this with the latest version of Electron and it appears to have been fixed.
