### ISSUE TITLE
The window opens only on the desktop where the application was opened

### ISSUE THREAD

**Issue by marcbachmann** [maxogden/menubar#43]
Currently if you click on the tray icon on a mac, the mac automatically switches to the desktop where the application was started. This window behaviour is not well suited for a tray application.
I'd like to change the current behaviour by using the `browserWindow.setVisibleOnAllWorkspaces(true)` option. This option is used to show the application on all workspaces.

**Comment by jenslind** [comment]
Yes, we have an open PR https://github.com/maxogden/menubar/pull/41

**Comment by marcbachmann** [comment]
This makes it also configurable :wink:

**Comment by rhysd** [comment]
Is there any use case where user wants to disable visible-on-all-workspace option?
