### ISSUE TITLE
Is there no app quit event?

### ISSUE THREAD

**Issue by stursby** [maxogden/menubar#56]
I'm trying to add a Quit button to my menubar app... but can't seem to figure it out.

I've tried `mb.quit()` and creating an `var app = require('app');` and then `app.quit()` per the [Quick Start Guide](http://electron.atom.io/docs/latest/tutorial/quick-start/) with no luck. Am I missing something?

Thanks.

**Comment by maxogden** [comment]
`menubar` doesn't modify anything related to electron app quitting, so you should be able to use the standard `.quit` method. you don't need to `require('app')`, its available as `mb.app` (see [docs](https://github.com/maxogden/menubar#usage)). my advice would be to try listening to the various quitting related events listed here to try and figure out whats going on https://github.com/atom/electron/blob/master/docs/api/app.md, and maybe to try closing all the app windows

**Comment by fabien-d** [comment]
`require( 'app' )` will only work in the main process. Are you trying to add the button in the renderer process? If so, you'll need to require the app using the `remote` module.

```js
var remote = require( 'remote' );
var app = remote.require( 'app' );

app.quit();
```

**Comment by stursby** [comment]
@fabien-d that worked, thank you! Also, thanks for the extra info @maxogden ;)
