### ISSUE TITLE
How to load a browser-window inside the tray window?

### ISSUE THREAD

**Issue by fjaguero** [maxogden/menubar#57]
Hi,

I just started to play with electron and I was trying to embed a browser-window inside de mb window but I couldn't make it. I didn't find the way to bind them both.

Thanks.

**Comment by maxogden** [comment]
@fjaguero the mb window is a browser-window. I am not sure what you mean exactly by embedding, maybe you mean `<iframe>`?

**Comment by fjaguero** [comment]
Sorry, yes. The thing is that I want to run a frameless external URL on the window.

**Comment by jenslind** [comment]
To load a external url, just set the url with the `index` option.
```
var mb = menubar({index: 'http://yourExternalUrl.com'})
```
If you want to change the url when the app is running use `mb.window.loadUrl()`

**Comment by fjaguero** [comment]
Awesome. Thanks :+1:
