### ISSUE TITLE
Menubar hides the dock icon

### ISSUE THREAD

**Issue by gurkerl83** [maxogden/menubar#62]
Electron-boilerplate provides a nice quick-start setup testing electron. In oder to reproduce this issue checkout the repo 
+ replace the amd-loader in build script like

```javascript
//.pipe(babel({ modules: 'amd' }))
.pipe(babel({stage: 0}))
```

+ replace script tags in app.html
```
<!--
<script src="vendor/require.js"></script>
<script>
requirejs(['app'], function (app) {});
</script>
-->
```

with 
```
<script src="app.js"></script> in body
```

+ include this in main.js
```javascript
var menuBar = require('menubar');
var mb = menuBar();
mb.on('ready', function ready () {
    console.log('app is ready')
});
```

+ now run the following commands
gulp build

install electron-prebuild globally
npm install -g electron-prebuilt

launch it with a global installation of electron-prebuild
electron ./build

Thanks

**Comment by jenslind** [comment]
Do you mean the icon in the dock? If so, menubar hides it by default.
You can show it by running `mb.app.dock.show()` in the ready event.

**Comment by gurkerl83** [comment]
This solved the issue. There are use cases where the dock hiding approach make sense. Please provide a optional field to let the developer to decide which scenario fits best.

Thanks

**Comment by stefanjudis** [comment]
Maybe we can make this configurable or improve the documentation to point out, that `menubar` is doing it.

Especially beginners are struggling with this, then debugging a while until finding out that `menubar` is hiding the dock icon.

cc. @radibit

**Comment by jenslind** [comment]
Yea, this should probably be configurable. :)

**Comment by stefanjudis** [comment]
Okay, I guess this means you're open for a PR? :P

**Comment by jenslind** [comment]
yes :)
