### ISSUE TITLE
Menubar instance has no reference to window

### ISSUE THREAD

**Issue by programbo** [maxogden/menubar#65]
```javascript
var menubar = require('menubar');

var mb = menubar();

mb.on('ready', function ready () {
  console.log('mb.window:', mb.window); // -> mb.window: undefined
});
```

According to the README, `mb` should contain `window`, the electron require('browser-window') instance. About to check the codebase for an obvious error or a way I can hack it in temporarily.

Using v2.2.1 on Mac OS X 10.10.3 and node v0.12.7.

**Comment by jenslind** [comment]
The window is not created until you click on the menubar icon.
You could use `preloadWindow` to create the window on start.

```
var mb = menubar({preloadWindow: true})
```

**Comment by programbo** [comment]
Perfect! `preloadWindow` also solves the initial content loading flash.
