### ISSUE TITLE
dynamically generate HTML instead of using file?

### ISSUE THREAD

**Issue by nealrs** [maxogden/menubar#66]
Hola. having lots of fun creating little mini menubar apps - thanks for building this bad jackson. That said, is it possible to dynamically generate HTML and feed it into the constructor like this? 

```js
var menubar = require('menubar');

var h = 
"<html><body>derp</body></html>";

var mb = menubar({
  'index' : h
});

mb.once('show', function () {
  mb.window.openDevTools();
});

```

**use case:** Use zombie.js to scrape a page, generate some new HTML form the data, and then display that HTML in my menu bar app. (and eventually, update it)

**Comment by maxogden** [comment]
Hmm I don't think so, we just pass the url option directly to electron `browser-window`: https://github.com/maxogden/menubar/blob/master/index.js#L85 and I don't think electron supports non-files at this time

**Comment by jenslind** [comment]
https://github.com/atom/electron/issues/968
https://github.com/atom/electron/issues/1146

**Comment by maxogden** [comment]
nice, that should work because we just pass `opts.index` to `loadUrl`: https://github.com/maxogden/menubar/blob/9e6042c00a5e9e84f028d31862350508d3510d1a/index.js#L97

**Comment by nealrs** [comment]
awesome thanks @jenslind that worked!
