### ISSUE TITLE
Menu doesn't show on Windows 10

### ISSUE THREAD

**Issue by jingweno** [maxogden/menubar#67]
The menu doesn't show up on Windows 10: https://github.com/jingweno/hacker-menu/issues/18#issuecomment-141335512

**Comment by jenslind** [comment]
Please provide the version of `menubar` and `electron` you are using.

**Comment by jingweno** [comment]
electron-prebuilt: 0.31.2, menubar: 2.2.1

**Comment by jingweno** [comment]
Any update on this? Thanks!

**Comment by jenslind** [comment]
@jingweno the menu shows up fine for me, have you tested with the example app in this repo?
Also, does it work if you position the window with the `x` `y` options?

**Comment by cppctamber** [comment]
I also cannot get the menu to show up, electron-prebuilt: 0.34.5, cloned from the repository today. I can see the little cat icon, but cannot do anything with it.

**Comment by tylwright** [comment]
Menu works fine for me too on Win 10 (1703).
