### ISSUE TITLE
Menu doesn't show on Ubuntu

### ISSUE THREAD

**Issue by jingweno** [maxogden/menubar#68]
The README says it may work for "some Linuxes". I wonder if you have a list. But I just tested it doesn't work for Ubuntu 14.04.

**Comment by jenslind** [comment]
Thats because `libappindicator1` is used on ubuntu.

See https://github.com/maxogden/menubar/pull/40

**Comment by jingweno** [comment]
FWIW, electron-prebuilt: 0.31.2, menubar: 2.2.1

**Comment by jingweno** [comment]
Any update on this? Thanks!

**Comment by roccomuso** [comment]
+1 thanks

**Comment by miguelmota** [comment]
+1
