### ISSUE TITLE
.showWindow() doesn't use default position

### ISSUE THREAD

**Issue by nickbytes** [maxogden/menubar#69]
Calling `mb.showWindow()` renders the window in the top right corner. Is it possible to specify this to show as if clicking the menubar?

**Comment by jenslind** [comment]
No, currently there is no way to get the tray icon position without clicking the icon. So we have to default it to top-right when the tray position is missing.

https://github.com/atom/electron/issues/2469

**Comment by nickbytes** [comment]
@jenslind, in an OS project like this, would it be my responsibility to close this issue now?

**Comment by maxogden** [comment]
@nickbytes I think it's the responsibility of whoever remembers first :P

**Comment by maxogden** [comment]
Reopened because https://github.com/atom/electron/issues/2469 is still open, if that gets implemented this can be supported

**Comment by jenslind** [comment]
This has been fixed in the latest version of electron.

`tray.getBounds()` has been added.

```javascript
mb.on('ready', function ready () {
  mb.showWindow(mb.tray.getBounds())
})
```

**Comment by jenslind** [comment]
Also added `tray.getBounds` to `showWindow` method, so you don't have to pass the bounds yourself.

**Comment by Thomas0c** [comment]
@jenslind Is there anything that is required in order to access `getBounds` from the `tray` object?
This is what `mb.tray` looks like on my end (latest build): 
```
Tray {
  popContextMenu: [Function],
  _events:
   { click: [ [Function], [Function: clicked] ],
     'double-click': [ [Function], [Function: clicked] ],
     'right-click': [Function],
     'balloon-click': [Function] },
  _eventsCount: 4 }
```
