### ISSUE TITLE
How to have a transparent browserWindow?

### ISSUE THREAD

**Issue by michahell** [maxogden/menubar#70]
The Electron docs only state that upon creation of a new BrowserWindow we can set transparency. there is no method to do this, and setting the property directly does not work.
It would be cool if we could just pass the same options object that we can pass to the BrowserWindow constructor, but to the menubar constructor...

Correct me if I'm wrong!

My use case is that I want to be able to control transparency and color of the background of the menubar app i'm making.

**Comment by jenslind** [comment]
> It would be cool if we could just pass the same options object that we can pass to the BrowserWindow constructor, but to the menubar constructor...

You can, the options passed to the constructor is also used when creating the window.
https://github.com/maxogden/menubar/blob/master/index.js#L84-L85

```javascript
var mb = menubar({transparent: true})
```
Should work. :)

**Comment by michahell** [comment]
Oh hey that's cool, didn't know! great, i'll try right away :)

**Comment by michahell** [comment]
Awesome, works. Although if you have the DevTools open, it does not have a transparent background but a white one. Remove the devtools or close it, and you have a transparent window!

**Comment by leilarrossi** [comment]
I am using transparent flag set to true, devtools can be toggled with Cmd Alt I and hidden by defaut, but electron window is not transparent. What could be the problem? This is for Mac.
Thank you

var mb = Menubar({
  icon: __dirname + '/app/app.png',
  tooltip: 'Some tool tip',
  index: `file://${__dirname}/app/app.html`,
  width: WINDOW_WIDTH,
  height: WINDOW_HEIGHT,
  preloadWindow: true,
  transparent: true
  ,resizable: false // doesn't make any difference, still not transparent
  ,skipTaskbar: true
  ,fullscreen: false
});

**Comment by leilarrossi** [comment]
Figured it out. We are using react-bootstrap and including css, it was messing up with transparency.
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">
Fixed by adding background-color: transparent; to html and body tags.
