### ISSUE TITLE
Javascript error in main process when running Example.app from `make build`

### ISSUE THREAD

**Issue by rkpatel33** [maxogden/menubar#73]
I am getting this error when running the .app file produced by `make build`. When I run it from the CLI with `npm start` it runs fine. Also runs on windows with an .exe file when pacakged up using electron-packager.

![image](https://cloud.githubusercontent.com/assets/3799489/10264241/0a600c32-69d4-11e5-914e-37b681e8027d.png)

**Comment by jenslind** [comment]
Are you running `npm run build`? Have you tried re-building it or reinstalled the dependencies?

**Comment by rkpatel33** [comment]
I just tried it by deleting the node_modules folder then running the
following, then opening the .app file. It all seemed to run correctly.


   - run npm install
   - run npm run build to make Example.app


______________________________________
Rishi K. Patel | Founder | *www.docnavapp.com <http://www.docnavapp.com>*
LinkedIn <https://www.linkedin.com/in/rkpatel33>

**Comment by cmalven** [comment]
I'm getting the exact same error after building the package for Darwin.

Mac OS X Yosemite 10.10.3

`Error: Cannot find module 'electron-positioned'`

This is after running `npm install` and `npm run build` with a clean (no `node_modules`) directory.

**Comment by jenslind** [comment]
Ah, It's the `--ignore` causing `electron-positioner` to be ignored.
The ignore string should be regex, so I guess electron-positioner gets matched. :)

@maxogden
Looks like we can just remove the ignore flag from the build script because the packages it is supposed to ignore is already ignored by default by `electron-packager`, right?

**Comment by jenslind** [comment]
I updated the build script, should work now! :)
https://github.com/maxogden/menubar/commit/13188e885d5a1cadeabcac9079100e3fd4963b33

**Comment by rkpatel33** [comment]
Thanks!

**Comment by cmalven** [comment]
Works like a charm.
