### ISSUE TITLE
Arrow

### ISSUE THREAD

**Issue by urre** [maxogden/menubar#78]
Hey, what's the best approach to add an arrow (like dropbox's menu bar app) on top of the box?

**Comment by jenslind** [comment]
Make the window transparent and add the arrow with css.

**Comment by urre** [comment]
thanks @jenslind, any examples out there using this with electron?

**Comment by jenslind** [comment]
The options passed to menubar is also used when creating the `browser-window`.
So, to make the window transparent:
```
var mb = menubar({transparent: true})
```

**Comment by urre** [comment]
thanks!

**Comment by leilarrossi** [comment]
Could you, please, be a bit more specific about adding an arrow with css?
Thanks!

**Comment by urre** [comment]
yes, i meant like this. A arrow on top of the menubar app window.

![arrow](https://cloud.githubusercontent.com/assets/307676/15150221/99967d78-16cc-11e6-9f0b-e3c87e86c46e.jpg)

**Comment by leilarrossi** [comment]
Do you mean it's an image or css class? If css class, on which element?
Thank you!

**Comment by urre** [comment]
css. What's the simplest solution?

**Comment by leilarrossi** [comment]
Oh, I am asking you how to add an arrow, I was hoping someone will post the code ;)

**Comment by urre** [comment]
Ah, And I'm the one who opened this issue/question  :) https://github.com/maxogden/menubar/issues/78#issue-112665990

**Comment by leilarrossi** [comment]
I am new to css and electron for that matter. I'll post the solution if I find one. Thank you for quick response!

**Comment by leilarrossi** [comment]
So, I have it working but can't make electron window transparent. It might be something specific to my application.
The idea is to hide electron window and create your own with css and add a border to a body ( please see myarrow:before class which makes an arrow)
@urre see if this helps you:
global css:
.myarrow {
    position: relative;
    padding: 12px 0;
}

html,
body {
    margin: 0 auto;
    overflow: hidden;
}

/**
 * Set `box-sizing` to `border-box` for all elements by default. This makes it
 * easier to ensure widths when adding padding and borders.
 */
html {
    box-sizing: border-box;
    font-family: sans-serif;
    -webkit-text-size-adjust: 100%;
}

*, *::before, *::after {
    box-sizing: inherit;
}

.myarrow:before {
    content: "";
    height: 0;
    width: 0;
    border-width: 0 8px 12px 8px;
    border-style: solid;
    border-color: transparent transparent white transparent;
    position: absolute;
    top: 0px;
    left: 50%;
    transform: translateX(-50%);
}

.page {
    background: #222332;
    display: flex;
    flex-direction: column;
    width: 340px;
    height: 540px;
    margin: 0 auto;
}

.darwin.page {
    border-radius: 5px;
    box-shadow: 0 5px 24px rgba(0, 0, 0, 0.7);
    overflow: hidden;
}

and html:
  <body class="myarrow">
    <div id="root" class="page darwin"></div>
    <script>
      (function() {
        const script = document.createElement('script');
        script.src = (process.env.HOT) ? 'http://localhost:3000/dist/bundle.js' : '../dist/bundle.js';
        document.write(script.outerHTML);
      }());
    </script>
  </body>

**Comment by leilarrossi** [comment]
html:
  <body class="myarrow">
    <div id="root" class="page darwin"></div>
    <script>
      (function() {
        const script = document.createElement('script');
        script.src = (process.env.HOT) ? 'http://localhost:3000/dist/bundle.js' : '../dist/bundle.js';
        document.write(script.outerHTML);
      }());
    </script>
  </body>
