### ISSUE TITLE
How am I suppose to run the project?

### ISSUE THREAD

**Issue by BuKinoshita** [maxogden/menubar#79]
# 1) Home am I suppose to run the project?
Should be just like running a normal Electron App? I have `electron-prebuilt` installed globally.

This should work, right?
```electron .```

This is what shows for me
![screenshot 2015-10-22 16 41 21](https://cloud.githubusercontent.com/assets/6929565/10677665/c3896238-78db-11e5-87ff-99b4e1be461d.png)

# 2) How do I load an `index.html`?

````
var menubar = require('menubar');
var mb = menubar();

mb.on('ready', function ready () {
  index: 'file://' + __dirname + '../index.html')
});
```

Nothing loads, just showing the same thing (image above).

**Comment by maxogden** [comment]
everything under 1 is correct (that is what Electron is supposed to be doing), but the syntax of the code in part 2 of your question is incorrect. the example code might be helpful for you: https://github.com/maxogden/menubar/tree/master/example

**Comment by BuKinoshita** [comment]
Okay, thanks!

I ran the example and as far as I understood, I have to have a index.html on the root of my project, right?

But is not calling any where (that's what confused me). My index.html is in a dist folder, is there a way to call a index inside a dist folder?

**Comment by maxogden** [comment]
@BuKinoshita you can put it wherever you want, you just need to update the `index` option to point to it
