### ISSUE TITLE
Smaller width results in window appearing too far to the right of icon

### ISSUE THREAD

**Issue by sbecker** [maxogden/menubar#8]
@maxogden - this is an awesome project, thanks for making it! it is going to let me build a little app i've been dreaming of for a while.

Small issue, if I use a width smaller than the default of 400:

In main.js:
`var mb = menubar({width: 200})`

Note location of window (to the right) compared to the icon (far left):

![screenshot 2015-04-29 11 58 51](https://cloud.githubusercontent.com/assets/1001/7398942/2ea27e24-ee67-11e4-8d67-9133520642d9.png)

Is this a bug or is there an easy way to make it stay centered below the icon?

**Comment by jenslind** [comment]
https://github.com/atom/electron/issues/1500

**Comment by jenslind** [comment]
https://github.com/maxogden/menubar/pull/10
