### ISSUE TITLE
Support right click menu on the tray

### ISSUE THREAD

**Issue by JocheBe** [maxogden/menubar#82]
Support a right click function for the tray icon like with caffeine:
Not clicked:
<img width="33" alt="screen shot 2015-11-03 at 11 33 33" src="https://cloud.githubusercontent.com/assets/11436890/10906077/f28ae48e-821e-11e5-85a8-29438596f9e8.png">
Left clicked:
<img width="32" alt="screen shot 2015-11-03 at 11 33 44" src="https://cloud.githubusercontent.com/assets/11436890/10906088/fce177cc-821e-11e5-92e1-89800b984457.png">
Right clicked:
<img width="183" alt="screen shot 2015-11-03 at 11 34 02" src="https://cloud.githubusercontent.com/assets/11436890/10906091/0d2d80d0-821f-11e5-82ae-01658c5bf6ed.png">

**Comment by davej** [comment]
You can do:
```js
menubar.tray.on('right-clicked', function(){});
```

**Comment by pzi** [comment]
Should be `right-click`, here is the API doc: https://github.com/atom/electron/blob/master/docs/api/tray.md#event-right-click-os-x-windows

**Comment by kahluagenie** [comment]
Apologies for bringing up a closed issue, but this is directly related to the question.

I'd like to have default menubar functionality trigger on right click while having my custom action on left click. If I use `menubar.tray.on('right-clicked', function(){});`, I pretty much have to reimplement most of what menubar provides in the first place, don't I? Or is there an easy way to do that?

I was able to easily add this feature to menubar by having a boolean option flag that would indicate if the default event is a 'click' or 'right-click' - it's a couple of lines of code. Is there any interest in adding such a feature?

Thanks!

**Comment by maxogden** [comment]
@kahluagenie yes you'd need to make a pull request to the menubar code to support a new option to make right click the default

**Comment by kahluagenie** [comment]
Cool! I'll make a PR within the next couple of days when I get some free time. Holidays are getting in my way of coding :)
