### ISSUE TITLE
Remove box-shadow from menubar

### ISSUE THREAD

**Issue by lalwanivikas** [maxogden/menubar#88]
If I access my menubar from windows other than desktop, I get box-shadow on the top from menubar:

<img width="708" alt="screen shot 2015-11-10 at 11 44 19 am" src="https://cloud.githubusercontent.com/assets/9963169/11055811/ce30081c-87a0-11e5-8d8f-bfd83b73d842.png">
## 

On desktop it looks better, but if we can remove border-radius from top edge it can look great. Just like other menubar apps.

<img width="684" alt="screen shot 2015-11-10 at 11 43 57 am" src="https://cloud.githubusercontent.com/assets/9963169/11055846/16ad6012-87a1-11e5-9922-ce06416f70de.png">

<img width="384" alt="screen shot 2015-11-10 at 11 48 53 am" src="https://cloud.githubusercontent.com/assets/9963169/11055851/27090e66-87a1-11e5-91a4-f1b609dd99e4.png">

**Comment by davej** [comment]
Doing `menu.window.focus()` should fix this.

**Comment by lalwanivikas** [comment]
@davej Nopes :( Doesn't work.

**Comment by lalwanivikas** [comment]
@davej Could this in any way be related to OS X Mavericks? because I have not upgraded to Yosemite.

**Comment by davej** [comment]
Possibly, I'm on Yosemite.

**Comment by lalwanivikas** [comment]
@davej Thanks for your quick replies :+1: 

I have one more question:
- is it possible to auto-refresh (reload) content whenever somebody clicks the icon to see latest scores?

**Comment by davej** [comment]
Sure, listen to menubar's `show` event and then send an IPC message to the renderer. You can do something like `location.reload()` in the renderer when it receives the IPC message.

**Comment by lalwanivikas** [comment]
@davej Thanks! Will try this and let you know if it works.

**Comment by indrasantosa** [comment]
Hi, is it possible to remove the border-radius on the top page?

**Comment by yceballost** [comment]
> Sure, listen to menubar's `show` event and then send an IPC message to the renderer. You can do something like `location.reload()` in the renderer when it receives the IPC message.

I tried to use event show to do this but I think that I am doing something wrong! I am very noob 😅 

This is my piece of code in main.js

mb.on("show", function show () {
  location.reload()
})

**Comment by davej** [comment]
@yceballost: it needs to be executed on the renderer, so you have to use IPC.

**Comment by yceballost** [comment]
Im very new with electron and I really see a lot of things about IPC, but honestly, i don't really know what is it 😂 

Have I add something to main.js to call ipc?

**Comment by amaurymartiny** [comment]
The initial question seems to be solved, the last posts are unrelated to the topic. I'm closing this.
