### ISSUE TITLE
Icon is overwritten when packaged

### ISSUE THREAD

**Issue by cremfert** [maxogden/menubar#91]
Hi,

first of all, thanks for this great piece of software!

I have an issue regarding the icon: when developing, I can set the icon perfectly like this:
`var mb = menubar({dir: __dirname, icon: 'Icon.png', preloadWindow: true, showDockIcon: true});`
but as soon as I use your electron-packager, the packaged app all the time shows the cat in the menubar instead of my icon.

Any ideas?
Thanks and best regards

**Comment by neal-morgansolar** [comment]
I had the same problem and solved it by converting the .png icon to an .ico file.

**Comment by jprberlin** [comment]
It worked for me if i did it like this:
```
icon: path.join(__dirname, 'public', 'icon' ,'menubar_icon.png')
```
Adapt the path to your local path.

**Comment by Banjerr** [comment]
I'm having this same issue. The strange thing is that converting the png to ico completely breaks the entire app.

**Comment by tkothe** [comment]
Thanks a lot @Banjerr et al! You guys saved my day! :)

**Comment by onmyway133** [comment]
@jprberlin @Banjerr It works. Many thanks
