### ISSUE TITLE
Window not appearing, even with Example app in clean install

### ISSUE THREAD

**Issue by Zarkoix** [maxogden/menubar#97]
My project's window is either not appearing when clicked, or throwing the error

>Uncaught Exception:
TypeError: menubar.window.loadURL is not a function
    at createWindow (/Users/Adam/Documents/git/DebateTimer/node_modules/menubar/index.js:98:22)
    at EventEmitter.appReady (/Users/Adam/Documents/git/DebateTimer/node_modules/menubar/index.js:56:7)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)

I just did a clean install of menubar into a clean directory, and tried to run the example file and it launches (without building) but clicking the icon will not open the window. 

From this I believe that the problem has to be with my system, and not necessarily the project I was working on.

Any help appreciated :)

Edit: project seems to load fine when running 
> electron .

in the command line, but running
> npm start

which is effectively the same command throws the error

**Comment by Zarkoix** [comment]
the error in my project is only thrown when preloadWindow is true

**Comment by egoist** [comment]
same issue, copy code from example, I can see the icon in menubar but nothing in dock, and when I click on the menubar icon nothing happens. no errors logged.

```
osx 10.11
menubar ^3.0.0
```

**Comment by jenslind** [comment]
The example is broken because of some API changes in Electron. I have updated the electron version in the example.

**Comment by Zarkoix** [comment]
Thanks :) it works now
