### ISSUE TITLE
Menubar window not showing index.html

### ISSUE THREAD

**Issue by jdp** [maxogden/menubar#98]
Menubar isn't loading index.html when the function is called, but then trying to load the exact same path in the `after-create-window` event works. Here's a test case reproducing it:

``` javascript
var menubar = require('menubar');

var mb = menubar({
  dir: __dirname,
  index: 'index.html',
});

// Also doesn't work
// var path = require('path');
// var mb = menubar({
//   index: path.join(__dirname, 'index.html')
// });

// Uncomment the after-create-window handler to get the same path to load
// mb.on('after-create-window', function() {
//   mb.window.loadURL(`file://${__dirname}/index.html`);
// });

```

Invoked like this:

``` bash
./node_modules/.bin/electron src/test-menubar.js
```

I noticed this when the default electron index.html showed up instead of mine when I didn't pass options to `menubar`.

Versions: OS X 10.9.5, electron-prebuilt 0.36.0, menubar 3.0.0

**Comment by jenslind** [comment]
Hello,

Try to add the file protocol to the `index` option.
```
var mb = menubar({
  index: 'file://' + path.join(__dirname, 'index.html')
})
```

**Comment by jdp** [comment]
Hi @jenslind, thanks, that worked.

**Comment by jenslind** [comment]
:+1:
